mekanism/Mekanism

- src/main/java/mekanism/generators/common/tile/TileEntityGasGenerator.java
This change fixes the issue I was seeing where gasGenerators are limiting energy output based on hydrogen burning even though ethylene, when burned, produces more energy. This fix only checks and sets the output when a new fuel is first put into the generator, or when the when the generator is loaded up in the world.
> Fix for #1997 gasGenerators incorrectly limiting output

- src/main/java/mekanism/common/inventory/container/ContainerGasTank.java
I don't think a day goes by where I don't shift-click my jetpack into the gas tank and when it ends up in the bottom slot I cry out in pain :cry: 
If 99.9999% of the time you open the gas tank to manually fill a jetpack or scuba tank, it makes sense to have items shift-click into the top slot rather than the bottom one. (And items in either of the gas tank slots will shift-click to the player inventory now as well.)
> Shift-click items to top (fill) slot

- src/main/java/mekanism/common/CommonProxy.java
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/item/ItemAtomicDisassembler.java
- src/main/java/mekanism/common/network/PacketConfigSync.java
- src/main/java/mekanism/generators/common/MekanismGenerators.java
I added two new config entries. 
One for the atomic disassembler energy usage for request #2146.
The second for the ethylene burn time as I always felt that ethylene produced too much gross power compared to how much is produced from a single piece of wheat. Lowering to burn time from 40 to 20 or even 10 seemed to make a better balance on the servers I have run.
> New config entries

- .gitignore
This ignores Minecraft Forge files in .gitignore. 
I found this annoying that i had to remove and re-add Forge to prevent that the Minecraft Forge files was commited.
> Ignores Minecraft Forge files in .gitignore.

- build.gradle
- build.properties
Fixed CodeChickenCore missing, unable to run in development envitoments without it.
I think this should not affect regular Mekanism builds, but think someone should look over and verify this.
> Added CodeChickenCore as dependency for development enviroments.

- src/main/java/mekanism/common/tile/TileEntityMetallurgicInfuser.java
Fixes #2268
(it was trying to auto-eject energy cells :P)
I checked all of the other TileComponentEjector instances for similar errors, the rest of them look okay.
> Fix Metallurgic Infuser not auto-ejecting output

- src/main/java/mekanism/common/content/miner/MOreDictFilter.java
Fixed OreDictionary filter in Miner not writing "requireStack" to NBT.
This solves issue #2330.
> Fixed OreDictionary filter in Miner not writing "requireStack" to NBT.

- src/main/java/mekanism/api/ItemRetriever.java
There was this unnecessary import that broke the latest MDK.
> Fixed Mekanism API

- src/main/java/mekanism/common/base/EnergyAcceptorWrapper.java
Code was incorrectly handling non-TileEntity possibilities thus causing an NPE. NPE is now fixed as the system now does not return a null value as easily.
> Fixing NPE from EnergyAcceptorWrapper.java not handling ticks

- build.gradle
- build.properties
- src/api/java/buildcraft/api/core/StackKey.java
- src/main/java/mekanism/common/FluidNetwork.java
- src/main/java/mekanism/common/content/boiler/BoilerTank.java
- src/main/java/mekanism/common/content/tank/DynamicFluidTank.java
- src/main/java/mekanism/common/item/ItemBlockMachine.java
- src/main/java/mekanism/common/item/ItemGaugeDropper.java
- src/main/java/mekanism/common/recipe/inputs/FluidInput.java
- src/main/java/mekanism/common/recipe/inputs/PressurizedInput.java
- src/main/java/mekanism/common/tile/TileEntityBoiler.java
- src/main/java/mekanism/common/tile/TileEntityDynamicTank.java
- src/main/java/mekanism/common/tile/TileEntityElectricPump.java
- src/main/java/mekanism/common/tile/TileEntityFluidicPlenisher.java
- src/main/java/mekanism/common/tile/TileEntityPortableTank.java
- src/main/java/mekanism/common/tile/TileEntityRotaryCondensentrator.java
- src/main/java/mekanism/common/tile/TileEntitySolarEvaporationController.java
- src/main/java/mekanism/generators/common/item/ItemBlockGenerator.java
- src/main/java/mekanism/generators/common/tile/TileEntityHeatGenerator.java
There is no need to depend on such a new version, it only frustrates users who cannot update. I have tested a custom build with this code on the very latest forge release, and everything fluid related works perfectly fine.
It will now build on Forge 1291 (the *recommended* version for users)
> Remove hard dep on unnecessarily new forge version

- src/main/java/mekanism/common/integration/MekanismHooks.java
So the respective transmitters can be used to attune a AE2 P2P bus.
For Energy P2P, if IC2 is installed, it uses IC2 - Otherwise it uses RF instead.
Since it probably wouldn't work to register both RF and EU P2P tunnels.
Please tell me if I'm missing anything on the mekanism side.
> Register transmitter items with AE2 P2P

- src/main/java/mekanism/common/content/transporter/StackSearcher.java
Fixes #2844.
Also, @aidancbrady you probably should release a 8.1.7 soon with the bugfixes. This is the second bug that crashes minecraft in singleplayer (bin bug was first), and will pretty much crash any server which uses logistical sorters on anything that uses sided inventories.
> Another bugfix.

- src/main/java/mekanism/common/integration/CCPeripheral.java
At least under a Linux and Windows environment using Java 7 or 8 when doing a call from ComputerCraft such as:
peripheral.call("right", "getStored") on an energy cube the call would always return "Error.". This addresses that bug.
> Fix for CC peripherals always throwing error.

- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
The method indexes (6 and 7) correspond to "removeOreFilter" and "reset" instead of "addOreFilter" and "removeOreFilter".
Fixed the two method indexes listed to the correct ones.
> Peripherals api includes invalid indexes for methods with string parameters

- src/main/java/mekanism/client/ClientProxy.java
scala.actors.threadpool.Arrays is depreciated in favour of java.util.Arrays.
Fixes issue: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
> Update ClientProxy.java to use new java arrays

- src/main/java/mekanism/common/multipart/PartSidedPipe.java
Make it possible to block connections with Chisels & Bits and other multiparts.
Fix #3640
> Added Occlusion Test for Pipes and Wires

- src/main/java/mekanism/common/block/BlockBasic.java
- src/main/java/mekanism/common/block/states/BlockStateBasic.java
Allow metal blocks, refined glowstone blocks, and refined obsidian blocks to be used for beacons.
> Allow metal blocks to be used for beacons

- src/main/java/mekanism/client/jei/MekanismJEI.java
I think an old JEI was using meta + the `ISubtypeInterpreter`, but it was not intended, and JEI does not do that now.
Right now, if you look up Mekanism stuff in JEI it shows all kinds of blocks instead of just the intended block.
This PR fixes the Mekanism `ISubtypeInterpreter` so that it differentiates machines and basic blocks again.
> Account for meta in the JEI ISubtypeInterpreter

- src/main/java/mekanism/common/content/tank/SynchronizedTankData.java
Currently, the dynamic tank will send update packet if stored fluid amount is changed even if the changed amount is very little and has no visual change(10000000->9999990) and wasting the server bandwidth. 
Instead of send change every time fluid amount changed. This edit will only send update packet when fluid level is noticeably changed saving a lot of bandwidth usage if the tank is actively getting filled and drained every tick.
> More dynamic tank network optimization

- src/main/java/mekanism/common/block/BlockPlastic.java
Breaking plastic blocks drops wrong colour. Also WAILA & TOP rendered the wrong color in the overlay.
With this fix, both are working as supposed.
Fix for #3954
> Fix for issue #3954

- src/main/java/mekanism/common/multipart/PartGlowPanel.java
- src/main/java/mekanism/common/multipart/PartSidedPipe.java
Created a pull request for the fix proposed by @Siern as stated in issue #3887.
Compiled and it's confirmed to be working. You can break all cables again without crashes.
If anyone is interested, you can compile it yourself using gradle
> Fix breaking of cables and glow panel, fixes #3887

- src/main/java/mekanism/common/tile/TileEntityBin.java
Adds support for ItemHandler capability, exposing the stored items as a 1 slot inventory.
Like the DSU interface I left it as non-sided, and added simulate parameters to the add/remove functions, in order to not duplicate functionality.
Subclass was used because getStackInSlot works differently.
Benefits: things like AE2 & Refined Storage should be able to work with bins without any external dependencies.
> Bin IItemHandler

- src/main/java/mekanism/generators/common/tile/turbine/TileEntityTurbineValve.java
Turbine declared it has the energy storage and cable outputter capability with hasCapability, but didn't provide them with getCapability.
Closes #4097
> Fix turbine not returning energy capability - Fixes #4097

- src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorPort.java
The reactor tries to extract the gas "steam". It'ss not registred in the GasRegistry. Therefor a GasStack with type null is being created, which could also throw a bunch of NPE's.
You're still able to extract steam as a fluid.
Fixes #4067
> Do not extract steam as a gas from a reactor - Fixes #4067

- src/main/java/mekanism/client/render/tileentity/RenderThermalEvaporationController.java
Thermal Evaporation Plant will no longer attempt to render with a fluid-level that is higher than its max capacity.
> Fix for #4233: out-of-bounds error in thermal evaporation render, which crashes client.

- src/main/java/mekanism/common/integration/IMCHandler.java
IMC messages aren't able to delete any recipe.
Fixed by changing the String to look at.
> Fix IMC recipe removal

- src/main/java/mekanism/common/transmitters/grid/InventoryNetwork.java
- src/main/java/mekanism/common/util/TransporterUtils.java
Allow pipes to connect to IItemHandler capability items and allow extraction from it. Insertion from pipes to IItemHandler not yet working.
> Allow pipes to connect to IItemHandlers

- src/main/java/mekanism/common/block/BlockGasTank.java
Resolves: #4232 
Currently the gas tank has a small bounding box, but is also a full cube which causes players to suffocate in them when walked into at head level and rubberbanding players when walked at feet level.
This commit changes:
- Gas tanks are non full blocks
- The bounding box aligned to 3/16th (0.1875) off a block
(Can be merged in 1.11 too)
> Change gastank to non full cube.

- src/main/java/mekanism/client/gui/GuiMekanism.java
- src/main/java/mekanism/client/gui/element/GuiElement.java
- src/main/java/mekanism/client/gui/element/GuiScrollList.java
Allows to use the mouse wheel to scroll in GuiScrollList. Mouse event is accessible on all GuiElements.
> Add scroll wheel support for GuiScrollList

- src/main/java/mekanism/common/tile/TileEntityFluidTank.java
Implements feature #4165
If the current fluidtank is active and contains no fluid, check if the fluidtank underneath has the same fluid.
If it's the same as the one being inserted, accept the fluid. If they aren't the same, do not accept the fluid.
If the fluidtank underneath will execute the same checks if active.
Original behaviour is the same with non active fluidtanks.
> Only allow same fluids in active fluidtank towers.

- src/main/java/mekanism/common/tile/TileEntityElectrolyticSeparator.java
Electrolitic separator contains  two instances of:
```java
public TileComponentUpgrade upgradeComponent = new TileComponentUpgrade(this, 4);
```
> fixed separator taking two upgrades instead of one

- src/main/java/mekanism/common/OreDictCache.java
As in 1.11 Forge no longer allows ItemStacks to be null, you can change this condition to check.isEmpty(), which also fixes #4418
> Fixed IllegalArgumentException in OreDictCache class

- src/main/java/mekanism/generators/common/block/BlockReactor.java
Also, you should consider changing all of your classes to implement ITileEntityProvider instead of extending BlockContainer and switch from ISidedInventory to Capabilities
Fixes #4420
> Fixed reactor blocks dropping wrong items

- .travis.yml
Sped up the check time of Travis. It only checked it, but somehow if defined explicitly together with a minimal CI workspace reduces the run time by 50%.
Ran it twice (once to create the build cache):
https://travis-ci.org/thommy101/Mekanism/builds/239091571
> Improve travis compile time

- src/main/java/mekanism/common/tile/TileEntityInductionPort.java
- src/main/java/mekanism/common/tile/prefab/TileEntityElectricBlock.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityUniversalCable.java
- src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorController.java
- src/main/java/mekanism/generators/common/tile/turbine/TileEntityTurbineValve.java
Using Math.min to limit it to the max value of an integer.
Math.round(double a) returns a long and casting a long which is greater than the max int to an int will do all kind of things but the things you want it to do.
> Fix integer overflows

- src/main/java/mekanism/client/render/item/BakedCustomItemModel.java
Changes BakedCustomItemModel to stop crashing during rendering (common cause Tinker's Construct trying to cache the Quads), by only doing special rendering stuff if 
1. We (current thread) have an OpenGL context, 
2. The Tesselator isDrawing.
Should fix #4448 and any such related.
> Prevent crashing during getQuads

- src/main/java/mekanism/common/Mekanism.java
Fixes cross mod integration of oredict metals. Dusts, ingots, blocks are now correctly registered with TinkersConstruct after moving registration of oredict entries to preinit instead of init.
Fixes #4463 and #4288
> Fix oredict registration, moved to preinit

- src/api/java/ic2/api/energy/prefab/BasicEnergyTile.java
- src/main/java/mekanism/api/Coord4D.java
- src/main/java/mekanism/client/gui/GuiChemicalCrystallizer.java
- src/main/java/mekanism/client/gui/GuiDigitalMinerConfig.java
- src/main/java/mekanism/client/gui/GuiLogisticalSorter.java
- src/main/java/mekanism/client/gui/GuiOredictionificatorFilter.java
- src/main/java/mekanism/client/jei/crafting/ShapelessMekanismRecipeWrapper.java
- src/main/java/mekanism/client/render/obj/GlowPanelModel.java
- src/main/java/mekanism/client/render/tileentity/RenderBin.java
- src/main/java/mekanism/common/block/BlockBasic.java
- src/main/java/mekanism/common/block/BlockBounding.java
- src/main/java/mekanism/common/integration/OreDictManager.java
- src/main/java/mekanism/common/integration/WailaDataProvider.java
- src/main/java/mekanism/common/inventory/container/ContainerElectricPump.java
- src/main/java/mekanism/common/item/ItemBlockBasic.java
- src/main/java/mekanism/common/item/ItemProxy.java
- src/main/java/mekanism/common/recipe/inputs/InfusionInput.java
- src/main/java/mekanism/common/recipe/inputs/MachineInput.java
- src/main/java/mekanism/common/tile/TileEntityAdvancedBoundingBlock.java
- src/main/java/mekanism/common/tile/TileEntityBin.java
- src/main/java/mekanism/common/tile/prefab/TileEntityContainerBlock.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- src/main/java/mekanism/common/util/RecipeUtils.java
- src/main/java/mekanism/generators/client/gui/GuiReactorLogicAdapter.java
- src/main/java/mekanism/generators/common/block/BlockGenerator.java
I found a way to get Idea to analyse for `null` being passed where `ItemStack` was expected and where `ItemStack` was compared with `null` and gave Mekanism a check over.
For some of them (especially the internal use ones) I've left the `!= null` there to ensure no null pointer errors - so you may wish to go over them to verify if they're still needed.
> More Null ItemStack / Null Comparison

- src/main/java/mekanism/common/integration/MekanismHooks.java
- src/main/java/mekanism/common/integration/OreDictManager.java
NB: this is mainly based on my for of AE2 for 1.11+, Applied Llamagistics.
1. Universal cables should be registered to be a ForgeEnergy tunnel attunement. You're free to register it conditionally as IC2 if you want though
2. Commented out recipes for Certus and Fluix processes, as I put back the integration on the AL side with its custom recipe system. I've left sand and nether quartz in because that's not exclusive to AL.
NB: this commit should **not** be merged to the 1.10 branch as such integration does not exist there.
> Suggested Integration Changes for AE2

- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/integration/IMCHandler.java
I noticed while working on Applied Llamagistics that IMC added recipes (e.g. crusher, enrichment) don't show in JEI - I assume this is because Mek's `LoadComplete` handler fires after JEI's.
So, two options: use the dedicated event or process in postInit.
`IMCHandler` could probably also be static since it's not directly an event handler - as far as Idea can tell it's only ever used in the one place.
The `LoadComplete` event seems to also be frowned upon judging from the Javadoc.
> Use FMLInterModComms.IMCEvent to process IMC messages

- src/main/java/mekanism/common/block/states/BlockStateMachine.java
- src/main/java/mekanism/common/item/ItemBlockMachine.java
- src/main/java/mekanism/common/tile/TileEntityFactory.java
Fix smelting factories default max energy value.
Adresses #4510 
The fix for getMaxEnergy isn't the nicest, but I couldn't think of an other way to fix it for all usages.
> [1.11] Different factory issues.

- build.gradle
- src/main/java/mekanism/api/ItemRetriever.java
- src/main/java/mekanism/api/energy/ICableOutputter.java
- src/main/java/mekanism/api/gas/IGasTransmitter.java
- src/main/java/mekanism/api/reactor/IFusionReactor.java
- src/main/java/mekanism/api/reactor/INeutronCapture.java
- src/main/java/mekanism/api/reactor/IReactorBlock.java
- src/main/java/mekanism/common/capabilities/Capabilities.java
- src/main/java/mekanism/common/capabilities/DefaultCableOutputter.java
Marked as deprecated, should be excluded from the MDK zip.
Tested with the Flux Networks from #4540 and it loads fine.
The capability is a complete dud, but in the unlikely event anyone does use the field in `Capabilities` they likely won't check it's non-null, which could cause issues.
> [1.10 - compat] add back removed interfaces (and the capability just in case) 

- src/main/java/mekanism/common/tile/TileEntityFactory.java
- src/main/java/mekanism/common/tile/component/TileComponentConfig.java
Fixes #4560 
I also noticed during my investigation that `IEnergyWrapper#getConsumingSides()` is no longer used anywhere in the project and `getOutputtingSides()` is only called in `CableUtils#emit(IEnergyWrapper)` so some code cleanup may be needed
> Fix issue with side configuration not respecting block orientation

- src/main/java/mekanism/common/util/FluidContainerUtils.java
The cherry pick of the 1.11 fluid handler code borked normal buckets it seemed. This reverts it and should let empty containers stack (and consumables should be handled too).
Needs testing. Closes #4573
> Fix 1.10 container empty code

- src/main/java/mekanism/api/Pos3D.java
https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/java/mekanism/api/Pos3D.java#L140
The mappings update caused Pos3D.translate(double, double, double) to return bogus values.
The commit in which the mappings were updated is a13ce7910dff40578174b1f5a395ef72dea4f88f
@thommy101 probably forgot to add "this." because the previous fieldnames didn't need them.
This causes bugs down the line like the Laser not firing due to it thinking it's firing from x: 1 y: 1 z: 1.
> [1.12] Fix bug in Pos3D due to mappings update

- build.gradle
I've tried to make as few changes as possible to the output filenames so it doesn't screw with any build script you have.
* `releaseJars` task was removed, `build` task now will generate all the jars
* `fullBuild` now depends on `build`
* new jar type `api` - basically identical to the MDK (so could replace), but has compiled classes and source (maven/gradle dep compatible I hope)
* new task `uploadArchives` will publish a maven tree to wherever `LOCAL_MAVEN` env variable points to (NB: `file//` is added in the script). This output just needs to be uploaded to a webserver
* a couple of `dependsOn` were moved inside their task definitions
> refactor build.gradle to support maven publishing

- src/main/java/mekanism/client/gui/GuiQuantumEntangloporter.java
- src/main/java/mekanism/common/block/BlockMachine.java
- src/main/java/mekanism/common/content/entangloporter/InventoryFrequency.java
- src/main/java/mekanism/common/frequency/Frequency.java
- src/main/java/mekanism/common/inventory/InventoryList.java
- src/main/java/mekanism/common/inventory/container/ContainerUpgradeManagement.java
- src/main/java/mekanism/common/item/ItemBlockMachine.java
- src/main/java/mekanism/common/tile/TileEntityQuantumEntangloporter.java
- src/main/java/mekanism/common/tile/component/TileComponentUpgrade.java
Implements #4503, #3846, and half of what #3953 wants.
As for #3953 I've not changed the amount by which tiles emit to pipes, but have increased the buffer capacity to the same as the ultimate tiers of cable/pipe/tube can handle, so in theory transmitters can *pull* at their full rate, on one side of the porter at least.
Frequency storage in the itemstack stores only the name & public/private flag, so private frequencies should attach themselves to the placing player (e.g. should it be different to the frequency's).
Anchor upgrade is copied from the teleporter - loads just the tile's chunk.
> Entangleporter Improvements

- src/main/java/mekanism/common/Mekanism.java
Adresses #4617 
Only solves 1 out of the 2 issues yet
Remaining: anything > 64 pullamount is ignored
> Fix TierConfig not loading on first start

- src/main/java/mekanism/common/inventory/container/ContainerPersonalChest.java
- src/main/java/mekanism/common/inventory/slot/SlotPersonalChest.java
Current behaviour is as follows:
The top 6 rows (the real slots for personal chest) disallow placing personal chests in them through SlotPersonalChest.
The other rows (the real player inventory) do allow placing/moving personal chests.
One exception to this is when the personal chest is opened from the hotbar, it disallowes moving the opened chest in the hotbar.
Adresses #4634
> Fix personal chests

- src/main/java/mekanism/common/util/MinerUtils.java
For #4637
Attempts to use reflection to call `getSilkTouchDrop`, and also fires off the harvest events so other mods can add their drops.
**Needs some more testing**, ~~I'm not entirely sure using the one `Method` object works for subclasses!~~ (EDIT: dirty testing indicates the overridden method is indeed called) I've only tested with a bare world.
Includes some null safety too for backporting to 1.10
> Miner utils getSilkTouchDrop

- src/main/java/mekanism/common/integration/forgeenergy/ForgeEnergyIntegration.java
Should fix #4645
Previously the forge integration was passing to RF methods, which now get stripped if RF isn't there.
@aidancbrady just to be sure, the `IStrictEnergyAcceptor` and kin accept Mekanism J, yes?
> refactor ForgeEnergyIntegration to translate to IStrict* Mekanism classes

- src/main/java/mekanism/common/integration/OreDictManager.java
Add a combiner recipe for 3 x Diamond Dust -> 1 x Diamond Ore. This is in line
with the rest of the dust recipes, and it doesn't allow getting infinite
diamonds, since even with fortune 3, you only get an average of 2.5 diamonds
(and thus 2.5 diamond dusts) per ore.
> Allow creating diamond ore with the combiner

- src/main/java/mekanism/common/frequency/FrequencyManager.java
This function is unused, and it never worked right anyway due to a bug.
> Fix #4710: remove the removeAll function

- src/main/java/mekanism/common/content/transporter/Finder.java
Added an extra sybtype check to the transporter finder, just like # 992
Fixes #4694
> Added subtype check to transporter finder

- src/main/java/mekanism/common/tile/TileEntityElectrolyticSeparator.java
Force the energy usage to be a constant and not modified by any electrical upgrades.
Fixes #4852
> Make electrolytic separator not so efficient.

- src/main/java/mekanism/tools/common/MekanismTools.java
The event listener used for spawning zombies and skeletons with swords and armor from this mod is using the non-specific parent event. This means that the logic for spawning mobs with these items is fired for all of the events that inherit from LivingSpawnEvent. This causes the logic to run in many situations where it shouldn't. Under dev environment conditions, there are two situations where this event is firing where it probably shouldn't be. 
1. CheckSpawn - This is fired when the game tries to see if a location is valid for a mob to spawn. This method is fired a lot, and doesn't always, or even usually result in a mob spawning. You don't need to fire this early to achieve the same effect. This also results in a lot of wasted operations since the mob doesn't always spawn. This would …
> Fixed armor spawning checks firing when they shouldn't.

- src/main/java/mekanism/common/BoxBlacklistParser.java
Prevents the log from being spammed with messages about this.
> move log on cardboard box blacklist outside loop

- src/main/java/mekanism/common/tile/prefab/TileEntityBasicBlock.java
Resolves xnet compatibility issue wherein an xnet cable touching a mekanism machine in a chunk loaded area may corrupt all xnet networks server-wide on server restart.
as per https://github.com/aidancbrady/Mekanism/issues/5104 and https://github.com/McJtyMods/XNet/issues/283
> Removed markDirty() call from TileEntityBasicBlock::onChunkLoad

- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/integration/MekanismHooks.java
The cost for redstone and lapis is lower than for the normal ores because Cyclic's versions of these have much lower yields, averaging only 2.2 redstone and 4.4 lapis per ore, even with fortune 3.
> Add combiner recipes for Cyclic's nether/end ores

- src/main/java/mekanism/common/chunkloading/ChunkManager.java
As noted, chunk loader was writing one key and reading another :)
> Fix #5285; chunk loader was writing [xyz] as key and reading [xyz]Coord

- src/main/java/mekanism/client/render/item/CustomItemModelFactory.java
Placing an energy cube in a Dank/Null causes the client to crash because of a couple UnsupportedOperationExceptions in CustomItemModelFactory.java.  Based on the instructions in the [forge documentation](https://mcforge.readthedocs.io/en/latest/models/advanced/ibakedmodel/) I made isBuiltInRenderer() return false and removed getItemCameraTransforms altogether because it exists in IBakedModel.  I was not able to find any problems after making these changes but if the exceptions existed for a reason that is still relevant I can try and fix it another way.  
A crash log of the problem can be found [here ](https://paste.dimdev.org/ucohilemov.mccrash) btw.  It's not particularly relevant because its fixed now, but if you're curious its there.
> fix crash with dank/null due to UnsupportedOperationException

- src/main/java/mekanism/common/config/GeneralConfig.java
- src/main/java/mekanism/common/integration/OreDictManager.java
Added two config entires to allow changing the drop chance of sawdust when processing planks and logs. These still default to the expected values but allow a config driven way of changing.
The other change is to add sticks to the crusher recipe list in order to make sawdust. This is to make it easier to produce sawdust for paper production and to make use of extra sticks.
> QOL improvement of sawdust drop chance config and sticks to sawdust

- src/main/java/mekanism/common/integration/forgeenergy/ForgeEnergyItemWrapper.java
- src/main/java/mekanism/common/util/MekanismUtils.java
Port https://github.com/mekanism-mod/Mekanism/commit/486e5d451
Skips the part of "clamping" longs as they already get clamped with `Math.round()` as documented by the javadocs https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#round-double-
> Clamp int for forge energy wrapper

- src/main/java/mekanism/common/base/IAdvancedBoundingBlock.java
- src/main/java/mekanism/common/content/transporter/TransporterPathfinder.java
- src/main/java/mekanism/common/tile/TileEntityAdvancedBoundingBlock.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/util/ChargeUtils.java
Fixed Logistical Transporters not sending stuff back to home locations. It looks like this was a bug introduced from a PR in the main branch from a while ago.
Also, fixed Digital Miner's charge slot inventory functionality by trashing ISidedInventory stuff in IAdvancedBoundingBlock
> Fix TransporterStack home locations & DM inventory interaction

- src/main/java/mekanism/api/gas/Gas.java
Tints for gases are int he format `0xRRGGBB` whereas for fluids the format is `0xAARRGGBB`. This means that mods like Blood Magic, Tinker's Construct, Ceramics, etc that obey they alpha value of fluids for rendering would render our liquids as invisible.
At some point it may make sense for us to also obey the alpha value for when we render fluid's but I am currently unaware of any fluids that actually make use of this feature.
> When creating fluids from gases set their alpha value to no transparency

- src/main/java/mekanism/client/ClientProxy.java
- src/main/java/mekanism/client/SparkleAnimation.java
- src/main/java/mekanism/common/CommonProxy.java
- src/main/java/mekanism/common/tile/TileEntityMultiblock.java
- src/main/java/mekanism/common/tile/TileEntityThermalEvaporationController.java
- src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorController.java
In c368692a3, the recursive search was changed to iterative. The big problem with both approaches, however is that as more and more positions are scanned, it takes longer to actually determine if the position was scanned. This PR introduces a radius which is used to get a fixed set of block positions to scan and as each position is scanned, particles are generated. This reduces memory footprint and avoids a O(n^2) search.
Not quite working yet; pending me not being on a plane. :)
> Introduce bounds to search for sparkles!

- src/main/java/mekanism/common/inventory/container/ContainerFactory.java
- src/main/java/mekanism/common/tile/TileEntityFactory.java
- src/main/java/mekanism/common/util/StackUtils.java
Changes:
- Ported and fixed `dfd5252cd`. In mainline it currently checks to compare if the new "input" stack is equal to what the recipe for that "input" will produce, makes it so that if you try to insert more iron ore when you have iron as an output it doesn't work. (This bug is fixed in this port)
- Improved performance of factory auto sort from `O(n^2)` to `O(n)`. This means worst case for an elite factory it does `14` checks instead of `49`, and if ultimate factories ever get added it will only have to do `18` instead of `81`.
- Don't allow auto sorting into slots where they can't process to the existing output.
- Don't allow inserting into slots where the item won't be able to be processed into the existing output.
> Port factory insertion

- etc/core/mcmod.info
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/integration/MekanismHooks.java
- src/main/java/mekanism/common/integration/OreDictManager.java
More direct port of:
```
d2f0c24e5
847e78004
3456396d7
fd638902a
26abf5086
```
I still would like to eventually do a similar thing that I was attempting to in #5347 where we dynamically add recipes for registered oredictionary entries and am keeping my local branch work on it so I can work on it again in the future; but for now it is too much of a mess and probably will cause more issues than it will fix so is not worthwhile to do for the merge.
> Ported metallurgy ore doubling and cyclic integration stuff

- src/main/java/mekanism/generators/client/render/RenderBioGenerator.java
improve rendering of bio generator model when fuel level is low
The GUI output also flickers annoyingly but I have yet to work out how to solve that (seems it may be that the while packet of energy generated is output at once)
> improve bio generator rendering slightly

- src/main/java/mekanism/common/tile/prefab/TileEntityEffectsBlock.java
Per the commentary on https://minecraft.curseforge.com/projects/mekanism?comment=230 - avoid scheduling any sounds for a machine that is fully muffled.
> Avoid scheduling a sound to be played if it's fully muffled.

- src/main/java/mekanism/common/integration/crafttweaker/handlers/MekaTypeUtils.java
- src/main/java/mekanism/common/integration/crafttweaker/handlers/MekanismHelper.java
- Exposes `getGas` via the call `mods.mekanism.mekaTypeUtils.getGas(string);`
This change is in its own class so that eventually if/when we add more types (such as making infuse type a proper type instead of a string), then we can add ways to get them in this class.
> Implement #5397 add a way to get CrT gas from string

- src/main/java/mekanism/common/tile/TileEntityFactory.java
- Improve the recipe check for if an item can go in an input slot based on the current output to use the cached recipes. This updates the cached recipe if it seems to be out of date with the information we know.
- Also fixes the null pointer in #5392 and #5394 caused by attempting to get the recipe output of a null recipe. (For when items attempt to be inserted if they don't have a recipe that they match)
- Include some partially implemented code for if we ever have PRC factories to make it easier to have them support this recipe check.
> Factory recipe check

- src/main/java/mekanism/common/tile/TileEntityFluidTank.java
- src/main/java/mekanism/common/tile/transmitter/TileEntitySidedPipe.java
1. Fix capacity of fluid tanks sometimes being incorrect when loading an empty fluid tank.
2. Make transmitter networks update and correct and broken connection data on load. (Probably fixes any broken networks/breaking networks seen in #4676 )
3. Properly mark the transmitters as dirty if the redstone mode changed during refresh:
Before point 3 for example with the setup seen below, if you turned on redstone sensitivity for the middle pipe, flicked the lever, and then teleported a thousand blocks away. Teleporting back and disabling the redstone sensitivity (while the lever is still flicked) would get it into the broken state seen below. This also could happen where if you had a redstone signal going to the middle pipe (from a non broken state) and toggled the middle pipe to being …
> Various fixes to data not loading properly

- src/main/java/mekanism/common/LaserManager.java
- src/main/java/mekanism/common/entity/EntityFlame.java
- src/main/java/mekanism/common/item/ItemAtomicDisassembler.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/util/MinerUtils.java
- src/main/java/mekanism/common/util/StackUtils.java
- Cleans up calls to world.playEvent, making it more clear which event is being called
- Made `MinerUtils` easier to read by cleaning up some of the logic so that it has less else branches calling `fallbackGetSilkTouch` this allowed me to also inline `fallbackGetSilkTouch` as it only was being called in one spot.
I still need to look more into #5453 and https://github.com/mekanism/Mekanism/issues/5453#issuecomment-489216976 to see if that is how we should do it or if there is a better way.
> Miner cleanup

- src/main/java/mekanism/api/MekanismAPI.java
- src/main/java/mekanism/api/transmitters/DynamicNetwork.java
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/item/ItemNetworkReader.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityMechanicalPipe.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityPressurizedTube.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityTransmitter.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityUniversalCable.java
- src/main/java/mekanism/common/transmitters/Transmitter.java
- src/main/java/mekanism/common/transmitters/grid/EnergyNetwork.java
- src/main/java/mekanism/common/transmitters/grid/FluidNetwork.java
- src/main/java/mekanism/common/transmitters/grid/GasNetwork.java
- src/main/java/mekanism/common/transmitters/grid/InventoryNetwork.java
`mekanism.api.transmitters.DynamicNetwork#possibleAcceptors` no longer seems to have its values used, so given it stores TileEntities, best to be rid of it to avoid being the cause of a memory leak.
Technically is a breaking change to the api hovever.
> Change unused map (values) to use a set

- src/main/java/mekanism/api/infuse/InfuseRegistry.java
- src/main/java/mekanism/client/gui/GuiFormulaicAssemblicator.java
- src/main/java/mekanism/common/base/IFactory.java
- src/main/java/mekanism/common/inventory/InventoryBin.java
- src/main/java/mekanism/common/inventory/container/ContainerFactory.java
- src/main/java/mekanism/common/inventory/container/ContainerMetallurgicInfuser.java
- src/main/java/mekanism/common/item/ItemAtomicDisassembler.java
- src/main/java/mekanism/common/recipe/BinRecipe.java
- src/main/java/mekanism/common/recipe/ingredients/ItemStackMekIngredient.java
- src/main/java/mekanism/common/recipe/outputs/ChanceOutput.java
- src/main/java/mekanism/common/recipe/outputs/ItemStackOutput.java
- src/main/java/mekanism/common/recipe/outputs/PressurizedOutput.java
- src/main/java/mekanism/common/tile/TileEntityBin.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/tile/TileEntityFactory.java
- src/main/java/mekanism/common/tile/TileEntityMetallurgicInfuser.java
- src/main/java/mekanism/common/tile/TileEntityOredictionificator.java
- src/main/java/mekanism/common/tile/prefab/TileEntityAdvancedElectricMachine.java
- src/main/java/mekanism/common/tile/prefab/TileEntityDoubleElectricMachine.java
- src/main/java/mekanism/common/util/StackUtils.java
- Checks NBT in more places to see if two itemstacks are stackable/the same
- Also fixes Gas Conversions checking stack size for if two items are the same.
Remaining spots:
- Filters (I believe they are meant to not be "advanced" enough to support NBT though if this is not the case I can modify it to check the NBT
- The miner has a couple spots for the replace stack comparison which I believe is the same as the filters I mentioned above
> Check ItemStack NBT for comparison in more places

- src/main/java/mekanism/common/tile/transmitter/TileEntityMechanicalPipe.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityPressurizedTube.java
Makes it so that we do not simulate draining more fluid than we have room for, in case there are things such as shown in #5512 where a liquid is only accepted in stages. This goes against the previous assumption that if we can take `x` units of something that means we can also take `x - 1` units.
I also made this change to pressurized tubes even though I do not believe there is anything that goes against this assumption for gas networks, but in case anyone ever decides to do something like that with our API, at least it will support it properly.
> Simulate amount the network has room for, rather than the amount that rate it can transfer at

- src/main/java/mekanism/common/util/CapabilityUtils.java
- src/main/java/mekanism/common/util/EmitUtils.java
- src/main/java/mekanism/common/util/GasUtils.java
- src/main/java/mekanism/common/util/PipeUtils.java
Rewrote pipe and gas utilities orginally to fix chunk loading ghosting. In which accessing a block in another chunk would ghost load the chunk. While I was in the methods I rewrote them to be more reusable in terms of code. Replacing existing loops and calls with lambda driven versions. This makes the code easier to read and recycles common implementation. While at the same time not costing anything in terms of performance.
> Reworked PipeUtils and GasUtils side access

- src/main/java/mekanism/common/recipe/inputs/MachineInput.java
Ignores the amount check for the default check. In commit https://github.com/mekanism/Mekanism/commit/7704846128290996717363bbdb51a180547757a2 the testEquality method started caring about the input stack size. As everywhere that uses `inputItemMatches` is part of a testEquality method (ignores stack size), I have gone ahead and removed the extra check. The one place the stack size mattered was `MachineInput#inputContains` which already has an additional check for the stack size anyways.
This should fix #5521
> Ignore amounts for inputItemMatches

- src/main/java/mekanism/common/block/BlockBounding.java
- src/main/java/mekanism/common/tile/TileEntityAdvancedBoundingBlock.java
- src/main/java/mekanism/common/tile/TileEntityBoundingBlock.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/tile/TileEntityFluidTank.java
- src/main/java/mekanism/common/tile/TileEntityInductionPort.java
- src/main/java/mekanism/common/tile/TileEntityThermalEvaporationBlock.java
- src/main/java/mekanism/common/tile/prefab/TileEntityElectricBlock.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityLogisticalTransporter.java
- src/main/java/mekanism/common/tile/transmitter/TileEntitySidedPipe.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityThermodynamicConductor.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityTransmitter.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityUniversalCable.java
- src/main/java/mekanism/common/util/CableUtils.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- src/main/java/mekanism/generators/common/block/BlockGenerator.java
Searched for usage of World#getTileEntity(BlockPos) replacing any instance that looked close to accessing another block with a check for isBlockLoaded.
> Added checks for is block loaded to several methods

- src/main/java/mekanism/common/base/IBoundingBlock.java
- src/main/java/mekanism/common/block/BlockBounding.java
- src/main/java/mekanism/common/block/BlockGasTank.java
- src/main/java/mekanism/common/block/BlockGlowPanel.java
- src/main/java/mekanism/common/block/BlockMachine.java
- src/main/java/mekanism/common/block/BlockTransmitter.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/tile/TileEntitySeismicVibrator.java
- src/main/java/mekanism/generators/common/block/BlockGenerator.java
Fixes how various blocks interact with:
- button placement
- redstone placement
- torch placement
- snow falling (#4838)
- fence/wall connections
There are still some blocks with "complex" models that return SOLID as their BlockFaceShape when potentially it would make more sense if they did not; however these are minor and for the most part any big outliers have been dealt with by this PR.
> Overwrite getBlockFaceShape for various blocks

- src/main/java/mekanism/client/gui/GuiFormulaicAssemblicator.java
- src/main/java/mekanism/common/integration/OreDictManager.java
- src/main/java/mekanism/common/inventory/container/ContainerFormulaicAssemblicator.java
- src/main/java/mekanism/common/tile/TileEntityFormulaicAssemblicator.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- Fixes the assemblicator to use `IRecpie.getRemainingItems` instead of only handling containers (see #5413)
- Changes the weird MekanismUtils method to just be used in the assemblicator for repair recipes
- Caches the IRecipe used when not using a formula (yay performance)
> Assemblicator Fixes for Transforming recipes

- src/main/java/mekanism/client/ClientPlayerTracker.java
- src/main/java/mekanism/client/ClientTickHandler.java
- src/main/java/mekanism/client/MekanismKeyHandler.java
- src/main/java/mekanism/client/sound/FlamethrowerSound.java
- src/main/java/mekanism/client/sound/GasMaskSound.java
- src/main/java/mekanism/client/sound/JetpackSound.java
- src/main/java/mekanism/client/sound/PlayerSound.java
- src/main/java/mekanism/client/sound/SoundHandler.java
- src/main/java/mekanism/common/CommonPlayerTickHandler.java
- src/main/java/mekanism/common/CommonPlayerTracker.java
- src/main/java/mekanism/common/PlayerState.java
- src/main/java/mekanism/common/item/ItemFlamethrower.java
- src/main/java/mekanism/common/item/ItemJetpack.java
- src/main/java/mekanism/common/item/ItemScubaTank.java
- src/main/java/mekanism/common/network/PacketFlamethrowerData.java
- Adds some null safety to PlayerSounds and only get the player object when needed
- Fix flame thrower not playing sounds (it still doesn't play a sound when first equipped but unused for other players)
- Cleaned up various logic and method readability in ClientTickHandler and CommonPlayerTickHandler
- Keep track of which sounds we have for a player by UUID instead of EntityPlayer reference. Also use a WeakReference in PlayerSound instead of directly saving the EntityPlayer object (gracefully falls back to last known x, y, z position if the reference gets cleaned up while a reference to PlayerSound is still stored). This should allow the GC to do its job a lot better.
- Updated PacketFlamethrowerData to be like the Jetpack and GasMask ones in terms of MODE_CHANGE, UPDATE, and FULL options …
> Fix a few issues with sound

- src/main/java/mekanism/common/config/GeneralConfig.java
- src/main/java/mekanism/common/item/ItemAtomicDisassembler.java
- Cleaned up the code for `ItemAtomicDisassembler`
- Added config options (#5571, #5481) for min, max damage and energy cost for attacking and using the Disassembler as a hoe (or shovel for grass to grass path).
- Previously it seemed that there was a value stored for how much power using the disassembler as a hoe should cost, but it did not seem to be used anywhere, so now there is, and it stops early in AOE hoeing if it stops having enough power to continue.
- Changed how damage works at power levels < 2000 for the atomic disassembler. Previously if the disassembler had 1000 energy remaining it would do full damage (10 hearts) and then drain the disassembler. Now it will do 6 hearts before draining the disassembler.
- Extracted information pertaining to the `Mode` of the disassembler to …
> Atomic Disassembler config

- src/main/java/mekanism/api/gas/GasTank.java
- src/main/java/mekanism/client/ClientProxy.java
- src/main/java/mekanism/client/gui/GuiAdvancedElectricMachine.java
- src/main/java/mekanism/client/gui/GuiMetallurgicInfuser.java
- src/main/java/mekanism/common/block/BlockBasic.java
- src/main/java/mekanism/common/config/GeneralConfig.java
- src/main/java/mekanism/common/content/transporter/TItemStackFilter.java
- src/main/java/mekanism/common/entity/EntityBabySkeleton.java
- src/main/java/mekanism/common/integration/crafttweaker/gas/IGasStack.java
- src/main/java/mekanism/common/integration/forgeenergy/ForgeEnergyCableIntegration.java
- src/main/java/mekanism/common/integration/tesla/TeslaCableIntegration.java
- src/main/java/mekanism/common/inventory/InventoryList.java
- src/main/java/mekanism/common/item/ItemAtomicDisassembler.java
- src/main/java/mekanism/common/recipe/machines/AmbientGasRecipe.java
- src/main/java/mekanism/common/tile/TileEntityBin.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/tile/prefab/TileEntityEffectsBlock.java
- src/main/java/mekanism/common/transmitters/grid/EnergyNetwork.java
- src/main/java/mekanism/common/transmitters/grid/FluidNetwork.java
- src/main/java/mekanism/common/transmitters/grid/GasNetwork.java
- src/main/java/mekanism/common/util/GasUtils.java
- src/main/java/mekanism/common/util/PipeUtils.java
- src/main/java/mekanism/generators/client/gui/GuiIndustrialTurbine.java
- src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorController.java
- src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorLogicAdapter.java
- src/main/resources/mekanism_at.cfg
Minor cleanup to code, removing unused access transformers and ensuring that all methods that override another have the `@Override` annotation. Should make it easier to not lose track of things when porting to 1.14 if the mappings change.
> Minor cleanup

- src/main/java/mekanism/common/tile/transmitter/TileEntitySidedPipe.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityTransmitter.java
Reconnect pipes across chunks when the chunk loads. This is the more proper fix to #4676 that I had thought was fixed, but once the network ghost chunk loading got fixed resurfaced. It was very easy to reproduce now that there is no ghost chunk loading so writing a fix was simple. The networks already were fixing themselves; however, the pipes across chunks were not getting properly informed to update their "connections" as well.
> Fix network connections across chunk loading

- src/main/java/mekanism/common/FuelHandler.java
- src/main/java/mekanism/common/base/EnergyAcceptorWrapper.java
- src/main/java/mekanism/common/entity/EntityRobit.java
- src/main/java/mekanism/common/integration/ic2/IC2Integration.java
- src/main/java/mekanism/common/integration/ic2/IC2ItemManager.java
- src/main/java/mekanism/common/integration/redstoneflux/RFIntegration.java
- src/main/java/mekanism/common/integration/tesla/TeslaIntegration.java
- src/main/java/mekanism/common/item/ItemBlockEnergyCube.java
- src/main/java/mekanism/common/item/ItemBlockMachine.java
- src/main/java/mekanism/common/item/ItemEnergized.java
- src/main/java/mekanism/common/item/ItemFreeRunners.java
- src/main/java/mekanism/common/tile/TileEntityInductionPort.java
- src/main/java/mekanism/common/tile/prefab/TileEntityElectricBlock.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityUniversalCable.java
- src/main/java/mekanism/common/util/ChargeUtils.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- src/main/java/mekanism/generators/common/MekanismGenerators.java
- src/main/java/mekanism/generators/common/item/ItemBlockGenerator.java
- src/main/java/mekanism/generators/common/tile/turbine/TileEntityTurbineValve.java
- Moved the various remaining energy conversion calls into Integration classes so that it is easier to read what value is actually being converted, without all the extra code for making sure it doesn't go past the data types bound.
> Energy conversion code deduplication

- src/main/java/mekanism/common/content/miner/ThreadMinerSearch.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
Make ThreadMinerSearch use a chunkcache to prevent possible CME's / other issues with non safe world access.
I have had to move the breakable check onto the main thread in canBreak, as 1.12.2 doesn't have the functionality to check this from the cache.
> [1.12.2] Make ThreadMinerSearch use a chunk cache.

- src/api/java/mekanism/api/Coord4D.java
- src/api/java/mekanism/api/transmitters/IBlockableConnection.java
- src/main/java/mekanism/common/base/ILogisticalTransporter.java
- src/main/java/mekanism/common/capabilities/basic/DefaultBlockableConnection.java
- src/main/java/mekanism/common/capabilities/basic/DefaultLogisticalTransporter.java
- src/main/java/mekanism/common/content/transporter/TransporterPathfinder.java
- src/main/java/mekanism/common/content/transporter/TransporterStack.java
- src/main/java/mekanism/common/tile/TileEntityBin.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/tile/TileEntityLogisticalSorter.java
- src/main/java/mekanism/common/tile/component/TileComponentEjector.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityLogisticalTransporter.java
- src/main/java/mekanism/common/tile/transmitter/TileEntitySidedPipe.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityTransmitter.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityUniversalCable.java
- src/main/java/mekanism/common/transmitters/TransmitterImpl.java
- src/main/java/mekanism/common/transmitters/TransporterImpl.java
- src/main/java/mekanism/common/transmitters/grid/EnergyNetwork.java
- src/main/java/mekanism/common/transmitters/grid/FluidNetwork.java
- src/main/java/mekanism/common/transmitters/grid/GasNetwork.java
- src/main/java/mekanism/common/transmitters/grid/InventoryNetwork.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- src/main/java/mekanism/common/util/TransporterUtils.java
Changes:
- Move things around a bit so more parts of the Transporter path finder make use of being able to use a temporary map as a cache for chunk lookup. (Speeds up `getTileEntity` calls a fair bit)
- Cleaned up logic around how path finding works, so that returning to the start location is properly handled. (#5335 ended up causing #5843 )
- Fixed a case where path finding exited too early due to a non direct path that works, and having a second arbitrary path just connected to the same network that "quickly" left the range so had a low score but was not in range of our max distance check. Previously we just exited, and now in that case we just stop checking that path but continue checking other potential paths we may have. (Image below)
The path to the left in the image does not lead …
> Improve Transporter path finding performance and accuracy

- src/additions/java/mekanism/additions/common/MekanismAdditions.java
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/world/GenHandler.java
Wrap world generator feature additions, baby mob spawn egg dispenser behaviour, and parrot imitation sounds inside a deferred work queue to force them to run on the main thread.
Don't worry about Forge's deprecated annotation on DeferredWorkQueue. They added it before writing a replacement for some weird reason, it's still the correct way to handle this at this moment.
> Add thread safety to world gen, spawn eggs, parrot sounds.

- src/main/java/mekanism/common/content/gear/mekasuit/ModuleMekaSuit.java
* Fix Electrolytic Breathing Unit not working when standing on a trapdoor in two block deep water
* Make Electrolytic Breathing Unit fill any chestplate item that can hold hydrogen
* Allow Electrolytic Breathing Unit to fill the item in the players main hand with hydrogen
This does not fix the issue with sprinting underwater.
This implements mekanism/Mekanism-Feature-Requests#45
> Make Electrolytic Breathing Unit fill any main hand item that can hold hydrogen

- src/main/java/mekanism/common/content/gear/mekasuit/ModuleChargeDistributionUnit.java
- Fix Charge Distribution Unit trying to charge full items and voiding Energy.
- I know this could technically still happen if something fills the EnergyHandler between the two insertEnergy calls, but i think thats rare enough that it isn't worth the effort to prevent it.
> Fix Charge Distribution Unit trying to charge full items and voiding Energy

- src/main/java/mekanism/client/render/RenderTickHandler.java
- src/main/java/mekanism/common/entity/EntityFlame.java
- src/main/resources/META-INF/accesstransformer.cfg
- Add player motion to the flame motion.
This PR currently fails to make the flames faster then then player, if the player is very fast, this is caused by how the vanilla method for shooting projectiles works.
> Make Flamethrower flames be always faster then the player causing them

- src/main/java/mekanism/client/gui/element/custom/GuiModuleScreen.java
- src/main/java/mekanism/common/config/GearConfig.java
- src/main/java/mekanism/common/content/gear/ModuleConfigItem.java
- src/main/java/mekanism/common/content/gear/mekatool/ModuleVeinMiningUnit.java
Added config option for disabling extended vein mining for the Meka-Tool, this also removes HUD and Module Tweaker UI for extended vein mining when disabled.
Think this is the way to best integrate it with the existing code.
> Added config option for disabling extended vein mining for the Meka-Tool

- build.gradle
- gradle.properties
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/certus_crystal_purification.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/certus_crystal_to_dust.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/certus_ore_to_crystal.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/certus_seed_to_purified_crystal.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/charged_certus_ore_to_crystal.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/fluix_crystal_purification.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/fluix_crystal_to_dust.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/fluix_seed_to_purified_crystal.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/nether_seed_to_purified_crystal.json
- src/datagen/main/java/mekanism/common/recipe/compat/AE2RecipeProvider.java
- src/datagen/main/java/mekanism/common/recipe/impl/MekanismRecipeProvider.java
Fixes #6479
For the record: Not a fan of the recipes that directly convert crystals and dusts into their purified variants.
The recipes that do this for seeds I find less offensive (although the energy requirement might be tweaked if your recipes support it), since it's similar to the good 'ol AE2Stuff crystal grower.
One implementation note: AE2 now exposes the API only in common startup since it's not thread-safe to do so in the Mod constructor. Since this is datagen, common setup never runs, so the public-facing API is never made available. That's the reasoning for grabbing the API instance from the internal class here, which is slightly less stable.
We are however not going to change the item IDs in 1.16.1 anymore anyway.
> Added back 1.12 recipes for Applied Energistics 2

- src/additions/java/mekanism/additions/common/block/plastic/BlockPlasticTransparent.java
- src/additions/java/mekanism/additions/common/block/plastic/BlockPlasticTransparentSlab.java
- src/additions/java/mekanism/additions/common/block/plastic/BlockPlasticTransparentStairs.java
- src/api/java/mekanism/api/text/EnumColor.java
* Make transparent plastic blocks, stairs and slabs color beacon beams
* add a warning to not change the returned value from EnumColor#getRgbCode
> Make transparent plastic blocks, stairs and slabs color beacon beams

- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/sky_stone_dust_to_sky_stone.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/sky_stone_to_dust.json
- src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/smooth_sky_stone_to_sky_stone.json
- src/datagen/main/java/mekanism/common/recipe/compat/AE2RecipeProvider.java
* Add an Crusher recipe to convert Sky Stone to Sky Stone Dust
* Add an Enrichment Chamber recipe to convert Sky Stone Dust to Sky Stone
* Add an Enrichment Chamber recipe to convert Smooth Sky Stone to Sky Stone
Atleast two of there recipes were so common in the 1.12.2 modpacks i played that i thought they were part of mekanism itself, as it seems like there weren't, this pr is correcting that.
Note that these recipes are mostly only useful in modpacks, as AE2 itself has no use for sky stone dust, and no way besides the grindstone to get it.
If the modpack only nature of two of these recipes makes them not fitting what mekanism should be feel free to close this pr.
> Add some Processing Integration for AE2 Sky Stone

- src/main/java/mekanism/common/block/BlockMekanism.java
- src/main/java/mekanism/common/block/basic/BlockSecurityDesk.java
- src/main/java/mekanism/common/util/NBTUtils.java
As mentioned in #6644 the current implementation of `NBTUtils#setResourceLocationIfPresent()` crashes a dedicated server because `ResourceLocation#isResourceNameValid() / ResourceLocation#func_217855()` is client-only, this PR fixes this by implementing it the same way it is done in 1.16.
Also fixes block placing trying to send a packet to all players on the client and not handling the placer being null.
> Implement NBTUtils#setResourceLocationIfPresent() the same way as in 1.16, fixes #6644

- .lgtm.yml
- build.gradle
- buildSrc/.gitignore
- buildSrc/src/main/groovy/mekanism/tasks/MergeJars.groovy
- gradle.properties
- Cleaned up deprecated Gradle calls
- Rewrote gradle calls slightly to remove the majority of IntelliJ warnings on the build.gradle file. The one change I am not too sure about is moving the maven publication to a closure and setting the project for it
- Copy the modified mods.toml file to the intellij build folder in addition to the gradle build folder. This only somewhat helps as the intellij runconfigs have the wrong paths for MOD_CLASSES by default, but now if they get manually fixed it can actually run now. (I didn't bother experimenting with manually specifying the values as I am fine with continuing to just use the gradlle intellij runconfigs
- Moved a lot of the all jar merge logic into a separate file and add support for merging tags that are added by multiple modules. In theory …
> Gradle cleanup

- src/main/java/mekanism/common/lib/frequency/IFrequencyHandler.java
- src/main/java/mekanism/common/lib/frequency/TileComponentFrequency.java
- src/main/java/mekanism/common/tile/TileEntityQuantumEntangloporter.java
- Add Configuration Card support for Quantum Entangloporter
- Add method to unset frequency for the above to work correctly when copying from a QE that does not have a frequency set
Hello, this is my first PR to Mekanism.
Let me know if the implementation is not desired (e.g. if Frequency shouldn't be copied or only copied if present and no "unset") or if there's some problems I missed due to low experience with code base.
I'm unsue if the `deactivate(type)` and `setNeedsNotify(type)` are required since the mek cables properly disconnect and reconnect without them, but were added to match with `setFrequencyFromData` just incase.
> Add Configuration Card support for Quantum Entangloporter

- src/api/java/mekanism/api/MekanismAPI.java
- src/api/java/mekanism/api/math/FloatingLong.java
- src/test/java/mekanism/api/math/FloatingLongPropertyTest.java
- src/test/java/mekanism/api/math/FloatingLongTest.java
-Added optimizing methods for commonly used division operations.
-Added test coverage for each of the new methods.
> Math API Division Optimization

- src/main/java/mekanism/common/base/MekFakeNetHandler.java
- src/main/java/mekanism/common/base/MekFakePlayer.java
This protects against mods that improperly try to send packets to fake players and then crash due to there being no network handler or network manager. I believe this should work fine (tested and it does fix the crash in question), but I am not sure if we need to be initializing it in some other way to properly let the weak reference be used. My guess is not given the connection manager and connection handler are only held onto by each other and the player, so they shouldn't be keeping the player from being GCd. I am also not positive that I am using the correct PacketDirection for our fake NetworkManager but truth be told even on the chance that I am wrong I don't think it will really make much of a difference.
> Create a fake network handler

- src/datagen/generated/mekanism/.cache/cache
- src/datagen/generated/mekanism/assets/mekanism/lang/en_ud.json
- src/datagen/generated/mekanism/assets/mekanism/lang/en_us.json
- src/datagen/main/java/mekanism/client/lang/MekanismLangProvider.java
- src/main/java/mekanism/common/MekanismLang.java
- src/main/java/mekanism/common/content/gear/mekasuit/ModuleMekaSuit.java
Adds a toggle to the Electrolytic Breathing Unit that dictates whether it will attempt to fill held items with hydrogen, as described in [this feature request](https://github.com/mekanism/Mekanism-Feature-Requests/issues/230).
Originally created based on [the 1.16.x branch](https://github.com/mekanism/Mekanism/pull/7128), this PR is based on the v10.1 branch.
> Implement Fill Held toggle for Electrolytic Breathing Unit (reupload)

- src/main/java/mekanism/client/ClientTickHandler.java
Change VisionEnhancement night vision effect to 15s (300 tick) to avoid flashing.
> Avoid VisionEnhancement night vision flashing

- src/api/java/mekanism/api/heat/HeatAPI.java
- src/generators/java/mekanism/generators/common/content/fission/FissionReactorMultiblockData.java
- src/generators/java/mekanism/generators/common/content/fusion/FusionReactorMultiblockData.java
- src/generators/java/mekanism/generators/common/content/gear/mekasuit/ModuleGeothermalGeneratorUnit.java
- src/generators/java/mekanism/generators/common/tile/TileEntityHeatGenerator.java
- src/generators/java/mekanism/generators/common/tile/fission/TileEntityFissionReactorPort.java
- src/generators/java/mekanism/generators/common/tile/fusion/TileEntityFusionReactorPort.java
- src/main/java/mekanism/client/gui/GuiThermalEvaporationController.java
- src/main/java/mekanism/common/capabilities/heat/BasicHeatCapacitor.java
- src/main/java/mekanism/common/capabilities/heat/CachedAmbientTemperature.java
- src/main/java/mekanism/common/capabilities/heat/ITileHeatHandler.java
- src/main/java/mekanism/common/capabilities/heat/MultiblockHeatCapacitor.java
- src/main/java/mekanism/common/capabilities/heat/VariableHeatCapacitor.java
- src/main/java/mekanism/common/content/boiler/BoilerMultiblockData.java
- src/main/java/mekanism/common/content/entangloporter/InventoryFrequency.java
- src/main/java/mekanism/common/content/evaporation/EvaporationMultiblockData.java
- src/main/java/mekanism/common/content/network/HeatNetwork.java
- src/main/java/mekanism/common/content/network/transmitter/ThermodynamicConductor.java
- src/main/java/mekanism/common/lib/multiblock/MultiblockCache.java
- src/main/java/mekanism/common/lib/multiblock/MultiblockData.java
- src/main/java/mekanism/common/tile/TileEntityQuantumEntangloporter.java
- src/main/java/mekanism/common/tile/base/TileEntityMekanism.java
- src/main/java/mekanism/common/tile/machine/TileEntityFuelwoodHeater.java
- src/main/java/mekanism/common/tile/machine/TileEntityResistiveHeater.java
- src/main/java/mekanism/common/tile/multiblock/TileEntityBoilerCasing.java
- src/main/java/mekanism/common/tile/multiblock/TileEntityThermalEvaporationBlock.java
- src/main/java/mekanism/common/tile/multiblock/TileEntityThermalEvaporationValve.java
- Make use of the biome's temperature in just about every ambient temperature calculation instead of just in the evaporation plant #6702
- Make the fission reactor's simulate environment method mirror the boiler one as there aren't exactly sides. Potentially these things should be multiplied by six so as to simulate each side?
- Fix an issue in `ITileHeatHandler#simulateAdjacent` where it was calculating temperature differential against the environment instead of against the sinks temperature, and also using an incorrect heat capacity. This needs verification that this change is correct, especially because of the change to how the sink's heat is handled.
- Move the evaporation plant's temp multiplier calculations to after the temperature is actually updated.
- Improve handling of how the …
> Fix a variety of issues relating to temperature

- src/datagen/generated/mekanism/.cache/cache
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/copper/clump/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/copper/dust/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/copper/shard/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/copper/slurry/dirty/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/gold/clump/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/gold/dust/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/gold/shard/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/gold/slurry/dirty/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/iron/clump/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/iron/dust/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/iron/shard/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/iron/slurry/dirty/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/lead/clump/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/lead/dust/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/lead/shard/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/lead/slurry/dirty/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/osmium/clump/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/osmium/dust/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/osmium/shard/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/osmium/slurry/dirty/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/tin/clump/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/tin/dust/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/tin/shard/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/tin/slurry/dirty/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/uranium/clump/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/uranium/dust/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/uranium/shard/from_raw_block.json
- src/datagen/generated/mekanism/data/mekanism/recipes/processing/uranium/slurry/dirty/from_raw_block.json
- src/datagen/main/java/mekanism/common/recipe/impl/OreProcessingRecipeProvider.java
With raw ore needing 3 ore for its processing recipe I thought it would useful to have a bulk recipe for the raw ore block that does 3 times as much but only had a single item input. This would also be nice if you didn't want to use a sorter to input into your processing line.
I experimented with it only requiring twice as much secondary input as a bulk efficiency thing, but I think it would probably be better to switch to 3 as the speed/power efficiency is probably enough of an advantage already.
I also organized the other processing recipes so I could make sure I wasn't missing any. I hope that's ok, if not I'm fine with putting them back where they were.
> Added raw block recipes and organized existing recipes

- src/main/java/mekanism/client/model/ModelAtomicDisassembler.java
I found this cuboid floating out in the middle of nowhere, but given its name, it seemed it was meant to be up at the same height as the other part with a similar name.
Where it was:
Where it is now:
- Fixes floating cuboid in rendering of Atomic Disassembler
> Fix floating cuboid in Atomic Disassembler model

- src/main/java/mekanism/common/command/RadiationCommand.java
- src/main/java/mekanism/common/lib/radiation/capability/DefaultRadiationEntity.java
Update mek radiation heal command and DefaultRadiationEntity radiation variable to set to baseline instead of 0
> Update mek radiation heal command to set to baseline instead of 0

- src/generators/java/mekanism/generators/common/content/fusion/FusionReactorMultiblockData.java
The computer method getProductionRate is set to return the same value as if calling getPassiveGeneration(false). Between these two methods, there is no computer method to show the actual energy being produced by the reactor.  Changing the second argument to true with getProductionRate returns the actual energy being produced.
> Update FusionReactorMultiblockData.java getProductionRate() to return actual production rate

- .github/workflows/codeql.yml
This avoid actions being alive for too long for no reason, there has been examples of actions being alive for 2 hours or even 6 hours (By default, GitHub Actions kills workflows after 6 hours if they have not finished by then.)
> Update CodeQL to include a timeout

- src/additions/java/mekanism/additions/common/MekanismAdditions.java
- src/defense/java/mekanism/defense/common/MekanismDefense.java
- src/generators/java/mekanism/generators/common/MekanismGenerators.java
- src/main/java/mekanism/common/Mekanism.java
- src/tools/java/mekanism/tools/common/MekanismTools.java
Ensures Mekanism modules are added in a thread-safe manner.
After Mekanism itself is loaded, modules are loading in parallel. In some occasions, modules access `Mekanism#loadedModules` concurrently in bad timings, which leads to an inevitable crash as plain `ArrayList` is not thread-safe. In my case, this triggers `IndexOutOfBoundException`.
Approach used in this PR is identical to the one used in 1.19.x. Newer versions of Mekanism introduced a synchronized `addModule` method, which solves the given issue.
https://github.com/mekanism/Mekanism/blob/ee5707f96155c0306f99b768212cb893d43b60e8/src/main/java/mekanism/common/Mekanism.java#L253-L255
> Ensure Mekanism modules are added in a thread-safe manner

- src/main/java/mekanism/common/config/GeneralConfig.java
This adds the `forge:raw_materials/` tag to the default allowed filters for the Oredictionificator. Should be pretty self explanatory.
> Add "raw_materials" to default oredictionificator filter
