- src/main/java/mekanism/common/BoxBlacklistParser.java
This is a fix for being able to put modded items into the cardboard box blacklist (issue #2069).
> [#2069] Fix for modded items being added to cardboardbox blacklist

- src/main/java/mekanism/common/item/ItemBalloon.java
- src/main/java/mekanism/common/network/PacketTransmitterUpdate.java
- src/main/java/mekanism/common/tile/TileEntityBasicMachine.java
- src/main/java/mekanism/common/tile/TileEntityChemicalCrystallizer.java
- src/main/java/mekanism/common/tile/TileEntityChemicalDissolutionChamber.java
- src/main/java/mekanism/common/tile/TileEntityChemicalInfuser.java
- src/main/java/mekanism/common/tile/TileEntityChemicalOxidizer.java
- src/main/java/mekanism/common/tile/TileEntityChemicalWasher.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/tile/TileEntityElectrolyticSeparator.java
- src/main/java/mekanism/common/tile/TileEntityFactory.java
- src/main/java/mekanism/common/tile/TileEntityMetallurgicInfuser.java
- src/main/java/mekanism/common/tile/TileEntityRotaryCondensentrator.java
No scary changes, just cleared some warnings.
Basically added default perameter to switch statements.
> Cleanup, cleared some warnings.

- src/main/resources/assets/mekanism/lang/no_NO.lang
I'm from Norway, so i took the time to transelate Mekanism into Norwegian ;-)
> Added Norwegian translation

- src/main/java/mekanism/common/tile/TileEntityInductionCasing.java
I've never done a pull request before. Anyway, this one adds a few functions for ComputerCraft with Induction Matrices:
- getEnergyStored() and getMaxEnergyStored() which both return RF values (so it matches the common signature of Open Peripherals, making existing CC scripts compatible with the Induction Matrix)
- getEnergyStoredMJ() and getMaxEnergyStoredMJ(), same as above but using Joules
- getLastOutput() and getOutputCap().
Honestly, I'm not very fond of those method names. But well, they are easy to change.
Nota: I have put this support on the basic induction block so a computer can be plugged pretty much anywhere on the structure (including edges and corners). Maybe it's best to put it on induction ports? I don't know.
> Added ComputerCraft support to Induction Matrix.

- src/main/java/mekanism/client/gui/GuiPasswordEnter.java
- src/main/java/mekanism/client/gui/GuiPasswordModify.java
Added the default transparent greyed out background to the
GuiPasswordEnter and GuiPasswordModify GuiScreen's.
> Added the default transparent greyed out background to GuiScreen's.

- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/block/BlockBasic.java
- src/main/java/mekanism/common/integration/MekanismHooks.java
> Some minor fixes.

- .gitignore
- src/main/java/mekanism/common/tile/TileEntityTeleporter.java
Thank you, @Gebatzens
Fixes #2943
Also add misc IDEA files to .gitignore
> Force the player's experience to sync when changing dimensions

- src/main/resources/assets/mekanism/lang/da_DK.lang
Please tell me, if something is off.
> Add Danish locale

- src/main/resources/assets/mekanism/lang/ru_RU.lang
Fixed mistakes in ru_RU.lang and made sentences readable
> Update rus locale

- src/main/resources/assets/mekanism/lang/fr_FR.lang
Hi, I tried to update the translation as far as I found differences. Feel free to tell me or correct yourself if I missed any change or made a mistake.
> Update fr_FR.lang for v9

- src/main/resources/assets/mekanism/lang/da_DK.lang
I also corrected a few mistakes I had previously made.
> Update Danish locale

- src/main/java/cofh/api/CoFHAPIProps.java
- src/main/java/cofh/api/energy/EnergyStorage.java
- src/main/java/cofh/api/energy/IEnergyConnection.java
- src/main/java/cofh/api/energy/IEnergyContainerItem.java
- src/main/java/cofh/api/energy/IEnergyHandler.java
- src/main/java/cofh/api/energy/IEnergyProvider.java
- src/main/java/cofh/api/energy/IEnergyReceiver.java
- src/main/java/cofh/api/energy/IEnergyStorage.java
- src/main/java/cofh/api/energy/ItemEnergyContainer.java
- src/main/java/cofh/api/energy/TileEnergyHandler.java
- src/main/java/cofh/api/energy/package-info.java
- src/main/java/cofh/api/package-info.java
- src/main/java/mekanism/common/CommonPlayerTickHandler.java
- src/main/java/mekanism/common/base/IAdvancedBoundingBlock.java
- src/main/java/mekanism/common/base/IEnergyWrapper.java
- src/main/java/mekanism/common/block/BlockMachine.java
- src/main/java/mekanism/common/multipart/PartUniversalCable.java
- src/main/java/mekanism/common/tile/TileEntityAdvancedBoundingBlock.java
And maybe fixes for 1.9. See commits for changelog
> 1.8.9 fixes

- src/main/java/mekanism/client/voice/VoiceOutput.java
> hopefully solving EOF & allocation problems

- src/main/java/mekanism/common/block/BlockPlasticFence.java
Missed a color meta state with the plastic fence.
> Fix wrong fence color - Fixes #3954

- src/main/java/mekanism/common/Mekanism.java
> Added compressed diamond, obsidian, and redstone to the ore dictionary.

- src/main/java/mekanism/common/transmitters/TransporterImpl.java
> Fix missed null ItemStack logistical transporter

- src/main/java/mekanism/client/gui/GuiDictionary.java
- src/main/java/mekanism/common/recipe/ShapedMekanismRecipe.java
- src/main/java/mekanism/common/recipe/ShapelessMekanismRecipe.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- src/main/java/mekanism/common/util/RecipeUtils.java
Fixes #4321 and #4319
Thanks to @allanf181 for finding the recipe bug
> Fix null Itemstacks in miner and recipes

- src/main/java/mekanism/common/world/GenHandler.java
Fixes #4304.
Changed as how Vanilla generates clay: /net/minecraft/world/biome/BiomeDecorator.java#143
Thanks to Kobata from the MMD discord for pointing where to add the +8 :)
> Fix saltgen offset

- src/main/java/mekanism/client/MekanismClient.java
- src/main/java/mekanism/client/gui/element/GuiSecurityTab.java
- src/main/java/mekanism/common/entity/EntityRobit.java
- src/main/java/mekanism/common/frequency/FrequencyManager.java
- src/main/java/mekanism/common/item/ItemBlockEnergyCube.java
- src/main/java/mekanism/common/item/ItemBlockGasTank.java
- src/main/java/mekanism/common/item/ItemBlockMachine.java
- src/main/java/mekanism/common/item/ItemPortableTeleporter.java
- src/main/java/mekanism/common/item/ItemRobit.java
- src/main/java/mekanism/common/network/PacketSecurityUpdate.java
- src/main/java/mekanism/common/util/SecurityUtils.java
- src/main/java/mekanism/generators/common/item/ItemBlockGenerator.java
> Fix more UUID changes. Fix Robit owner.

- src/main/java/mekanism/tools/item/ItemMekanismAxe.java
Fixes #4122
NOTE: target branch is 1.10, can also be cleanly merged in 1.11.
> Allow axe specific enchantments on axe

- src/main/java/mekanism/common/CommonProxy.java
- src/main/java/mekanism/common/MekanismSounds.java
I couldn't find anywhere where you register your sound effect with the GameRegistry, so I added it to MekanismSounds. This seems to fix #3638 on dedicated servers (no issue on client integrated server)
> Register sounds with the GameRegistry

- src/main/resources/assets/mekanism/lang/ru_ru.lang
Synchronized language IDs with en_US.lang.
Added missed translations.
Fixed wrong translations (for example "brine", "slurry" etc.) and long (doesn't fit to GUI) translation.
> Updated Russian translation

- src/main/java/mekanism/common/integration/OreDictManager.java
Resolves https://github.com/aidancbrady/Mekanism/issues/4414
> Remove unused variable causing ClassCastException

- src/main/java/mekanism/common/content/transporter/Finder.java
> Allow all items to be filtered on modid

- src/main/java/mekanism/common/util/MekanismUtils.java
> Fix unsave cast RecipeList

- src/main/java/mekanism/common/tile/TileEntityFluidicPlenisher.java
> Process Fluidic Plenisher nodes from closest to furthest.

- src/main/resources/assets/mekanism/lang/cs_cz.lang
- src/main/resources/assets/mekanism/lang/de_de.lang
- src/main/resources/assets/mekanism/lang/en_us.lang
- src/main/resources/assets/mekanism/lang/fr_fr.lang
- src/main/resources/assets/mekanism/lang/it_it.lang
- src/main/resources/assets/mekanism/lang/ja_jp.lang
- src/main/resources/assets/mekanism/lang/pt_br.lang
- src/main/resources/assets/mekanism/lang/pt_pt.lang
- src/main/resources/assets/mekanism/lang/ru_ru.lang
> Update entity names.

- src/main/java/mekanism/generators/common/tile/turbine/TileEntityTurbineCasing.java
> Add missing null structure check.

- src/main/java/mekanism/common/content/transporter/InvStack.java
> [1.11] Fix logistical sorter handling with less than full stacks.

- src/main/java/mekanism/common/inventory/InventoryPersonalChest.java
> [1.11] Fix missing null itemstack in InventoryPersonal.

- src/main/java/mekanism/client/gui/GuiChemicalDissolutionChamber.java
- src/main/java/mekanism/client/gui/GuiChemicalInfuser.java
- src/main/java/mekanism/client/gui/GuiChemicalOxidizer.java
- src/main/java/mekanism/client/gui/GuiChemicalWasher.java
- src/main/java/mekanism/client/gui/GuiDigitalMiner.java
- src/main/java/mekanism/client/gui/GuiElectricPump.java
- src/main/java/mekanism/client/gui/GuiEnergyCube.java
- src/main/java/mekanism/client/gui/GuiFactory.java
- src/main/java/mekanism/client/gui/GuiFluidicPlenisher.java
- src/main/java/mekanism/client/gui/GuiInductionMatrix.java
- src/main/java/mekanism/client/gui/GuiLaserAmplifier.java
- src/main/java/mekanism/client/gui/GuiMatrixStats.java
- src/main/java/mekanism/client/gui/GuiRobitMain.java
- src/main/java/mekanism/client/gui/GuiRotaryCondensentrator.java
- src/main/java/mekanism/client/gui/GuiTeleporter.java
- src/main/java/mekanism/client/gui/element/GuiEnergyGauge.java
- src/main/java/mekanism/client/gui/element/GuiPowerBar.java
- src/main/java/mekanism/common/item/ItemBlockMachine.java
- src/main/java/mekanism/common/item/ItemEnergized.java
- src/main/java/mekanism/common/item/ItemFreeRunners.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- src/main/java/mekanism/generators/client/gui/GuiIndustrialTurbine.java
- src/main/java/mekanism/generators/client/gui/GuiReactorController.java
- src/main/java/mekanism/generators/client/gui/GuiReactorFuel.java
- src/main/java/mekanism/generators/client/gui/GuiReactorHeat.java
- src/main/java/mekanism/generators/client/gui/GuiReactorStats.java
- src/main/java/mekanism/generators/client/gui/GuiSolarGenerator.java
- src/main/java/mekanism/generators/client/gui/GuiTurbineStats.java
- src/main/java/mekanism/generators/client/gui/GuiWindGenerator.java
- src/main/java/mekanism/generators/common/item/ItemBlockGenerator.java
> [1.11] Add max energy to tooltips

- src/main/java/mekanism/common/util/FluidContainerUtils.java
Fixes #4539.
Also added some null checks and fixed some compiler warnings
> [1.11] Fix handling of consumable item fluid containers.

- src/main/java/mekanism/common/block/BlockBasic.java
If there's no space, drop them in front of the bin.
Adds feature #3807
> [1.11] Add bin drops directly to player inventory.

- src/main/java/mekanism/common/item/ItemBlockCardboardBox.java
- src/main/java/mekanism/common/item/ItemBlockGasTank.java
- src/main/java/mekanism/common/item/ItemBlockMachine.java
Makes Cardboardboxes, gastanks and fluidtanks stackable. Bins are already stackable.
Fixes #3802
> [1.11] Make empty containers stackable.

- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/generators/common/MekanismGenerators.java
> [1.11] Add multiblock structures to cardboard blacklist.

- src/main/java/mekanism/common/util/FluidContainerUtils.java
Fixes #4539.
Basically Tom's changes, plus changed to passing around the FluidHandler instead of the itemstack.
Tested with Buckets, Forestry cans & mek tanks.
> Fix handling of consumable item fluid containers.

- src/main/java/mekanism/common/content/transporter/TransporterPathfinder.java
Fixes #4437
Add checks to TransporterPathfinder to make sure the current node is able to emit to the side(s) we're about to check.
> Update Transporter Pathfinder

- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/tile/TileEntityElectricPump.java
- src/main/java/mekanism/common/tile/TileEntityFluidicPlenisher.java
> Fix config caching of pump, miner and plenisher.

- src/main/java/mekanism/client/render/RenderResizableCuboid.java
- src/main/java/mekanism/client/render/tileentity/RenderThermalEvaporationController.java
Simplified it a little and fixed it's lagginess, now it generates max 17 Display Instances per fluid ;)
Fixes #4425
> Fixed evaporator liquid rendering

- src/main/java/mekanism/common/content/transporter/InvStack.java
- src/main/java/mekanism/common/tile/TileEntityElectrolyticSeparator.java
1. Logistical transporter may lost items
2. Electrolytic separator may generated more gases.
> To fixed some problem.

- src/main/java/mekanism/client/jei/MekanismJEI.java
> Add JEI interpreter gastank and enerygcube

- src/main/java/mekanism/api/transmitters/TransmitterNetworkRegistry.java
- src/main/java/mekanism/common/multiblock/UpdateProtocol.java
> Move some recursion to queues

- src/main/java/mekanism/common/item/ItemSeismicReader.java
- src/main/resources/assets/mekanism/lang/en_us.lang
Added some information about usage to the Seismic Reader, almost the same as the Seismic Vibrator.
Adds feature #4743
Opened as PR to make sure the used wording for the tooltip is right ;)
> Add tooltip information to Seismic Reader

- src/main/java/mekanism/api/MekanismAPI.java
- src/main/java/mekanism/api/MekanismRecipeHelper.java
- src/main/java/mekanism/api/gas/Gas.java
- src/main/java/mekanism/api/gas/GasRegistry.java
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/recipe/APIHandler.java
Some API updates that the MMD guys wanted.
Seeking feedback on the recipe stuff; IMC is good, but seems undocumented and people don't like it. Implemented a recipe helper which does a basic sanity check.
> Api update

- src/api/java/cofh/api/item/IToolHammer.java
- src/main/java/mekanism/api/IMekWrench.java
- src/main/java/mekanism/common/block/BlockBasic.java
- src/main/java/mekanism/common/block/BlockEnergyCube.java
- src/main/java/mekanism/common/block/BlockGasTank.java
- src/main/java/mekanism/common/block/BlockMachine.java
- src/main/java/mekanism/common/block/BlockTransmitter.java
- src/main/java/mekanism/common/integration/MekanismHooks.java
- src/main/java/mekanism/common/integration/wrenches/BuildCraftProxy.java
- src/main/java/mekanism/common/integration/wrenches/CofhProxy.java
- src/main/java/mekanism/common/integration/wrenches/IC2Proxy.java
- src/main/java/mekanism/common/integration/wrenches/MekPassthrough.java
- src/main/java/mekanism/common/integration/wrenches/MekWrenchProxy.java
- src/main/java/mekanism/common/integration/wrenches/Wrenches.java
- src/main/java/mekanism/common/item/ItemConfigurator.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- src/main/java/mekanism/generators/common/block/BlockGenerator.java
Adds back COFH hammer to the Configurator & adds generic (and extensible) 3rd party wrench handling.
> Wrench compat

- src/main/resources/assets/mekanism/lang/pl_pl.lang
Fixed 3 variables that changed in the process of creating new module versions. Fixed an invalid name. The names of cables and pipes are correct for the Polish language.
> final update pl_pl.lang

- src/main/java/mekanism/common/tile/TileEntityGasTank.java
Fixes #4867.
Do not merge yet, needs some testing.
> Allow extraction from gastanks.

- src/main/java/mekanism/common/Mekanism.java
Adds feature #4814.
Opened as PR to discuss used values.
> Add (char)coal blocks to infuser.

- src/main/java/mekanism/common/tile/prefab/TileEntityElectricBlock.java
I'm hoping this fixes it, but when are these things actually this easy?
> This is never this simple, what am I missing?

- src/main/java/mekanism/client/gui/GuiAdvancedElectricMachine.java
- src/main/java/mekanism/client/gui/GuiFactory.java
Found these two places that the rendering needed to be fixed, after the change to tints.
> Fixes Gas Color rendering in machine Gui's

- src/main/java/mekanism/common/base/ItemHandlerWrapper.java
- src/main/java/mekanism/common/content/transporter/TransporterManager.java
- src/main/java/mekanism/common/util/InventoryUtils.java
In regard to https://github.com/mekanism-mod/Mekanism/issues/5162
> Adds validation checks for insert into IItemHandler

- src/main/java/mekanism/api/MekanismAPI.java
- src/main/java/mekanism/client/MekanismClient.java
- src/main/java/mekanism/common/CommonProxy.java
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/network/PacketBoxBlacklist.java
Ported the following commits:
```
8c06618a7
451d950c5
6934e8b43
52d809ba5
35db7373a
6b69c82ea
```
And added a couple minor helper methods to make it easier to read the code.
> Box blacklist

- src/main/java/mekanism/common/item/ItemPortableTeleporter.java
- src/main/java/mekanism/common/tile/TileEntityTeleporter.java
> Dont do distance calculation when teleporting between dimensions

- src/main/java/mekanism/client/ClientPlayerTracker.java
- src/main/java/mekanism/client/ClientTickHandler.java
- src/main/java/mekanism/client/render/RenderTickHandler.java
- src/main/java/mekanism/common/CommonPlayerTracker.java
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/PacketHandler.java
- src/main/java/mekanism/common/PlayerState.java
- src/main/java/mekanism/common/network/PacketFlamethrowerData.java
- src/main/java/mekanism/common/network/PacketFreeRunnerData.java
- src/main/java/mekanism/common/network/PacketJetpackData.java
- src/main/java/mekanism/common/network/PacketScubaTankData.java
Port parts of `32b040353`. Does not include part having to do with capes, instead that is mentioned https://github.com/mekanica/mekanica/issues/138 so as to not be misplaced if it turns out to be needed.
> Keep track of active modes via uuid's instead of names

- src/main/java/mekanism/common/integration/MekanismHooks.java
- src/main/java/mekanism/common/recipe/inputs/AdvancedMachineInput.java
- src/main/java/mekanism/common/recipe/inputs/DoubleMachineInput.java
- src/main/java/mekanism/common/recipe/inputs/InfusionInput.java
- src/main/java/mekanism/common/recipe/inputs/ItemStackInput.java
- src/main/java/mekanism/common/recipe/inputs/MachineInput.java
- src/main/java/mekanism/common/recipe/inputs/PressurizedInput.java
> Allow custom item matching in recipe inputs

- src/main/java/mekanism/common/tile/prefab/TileEntityBasicBlock.java
> Fix energy cubes missing the spinny cube on load/enter area

- build.gradle
- gradle.properties
Port of the following commits:
```
e3a2fa1cc
5aabf2653
```
> Port AE2 gradle changes

- src/main/java/mekanism/api/gas/GasTank.java
> Ensure some edge cases with GasTank stack having 0 amount can't happen

- src/main/java/mekanism/common/recipe/RecipeHandler.java
> Put recipe values as an immutable list

- src/main/java/mekanism/client/render/obj/MekanismOBJModel.java
- src/main/java/mekanism/client/render/obj/OBJBakedModelBase.java
> Fix missing texture warnings

- src/main/java/mekanism/common/block/BlockBounding.java
- Port of `2d9d5463a`
- Removed no longer needed try/catch blocks.
> Make BlockBounding more aware of main pos

- src/main/java/mekanism/common/util/ChargeUtils.java
- Port parts of `ebf1542ac` (some of it was unneeded)
- Make ChargeUtils easier to read by splitting some compound boolean expressions into multiple if statements.
- Change order of attempted energy types (in ChargeUtils) to:
- Ours
- Forge
- RF
- Tesla
- IC2
> Minor cleanup to Charge Utils

- src/main/java/mekanism/client/ClientProxy.java
> Fall back to FMLCommonHandler if world is not WorldServer where we otherwise expected it to be

- src/main/java/mekanism/common/base/EnergyAcceptorWrapper.java
- Port of `588fc13ce`
- Change order of attempted energy types (in EnergyAcceptorWrapper) to:
- Ours
- Forge
- RF
- Tesla
- IC2
> Add some null safety for EnergyWrapperAcceptor(s).

- src/main/java/mekanism/common/content/miner/ThreadMinerSearch.java
- Port of `ce18f1043`
- Removed an unused try/catch. (I couldn't find any cases when it would get used)
> Use less world access in digital miner thread

- src/main/java/mekanism/client/sound/SoundHandler.java
> Fix once-off sound event playing using volume option for pitch

- build.gradle
- gradle.properties
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/tile/TileEntityAdvancedBoundingBlock.java
- src/main/java/mekanism/generators/common/MekanismGenerators.java
- src/main/java/mekanism/tools/common/MekanismTools.java
- Port `d303295` Move all version number references to gradle based
- Port `ebb0c46` don't set main multiblock position to air if its not loaded or not the right tile. Log if its not null but not what we expect
> Port a couple missed commits

- src/main/java/mekanism/client/gui/GuiDynamicTank.java
- src/main/java/mekanism/client/gui/GuiThermoelectricBoiler.java
- src/main/java/mekanism/client/gui/element/GuiFluidGauge.java
- src/main/java/mekanism/client/render/FluidRenderMap.java
- src/main/java/mekanism/client/render/FluidRenderer.java
- src/main/java/mekanism/client/render/MekanismRenderer.java
- src/main/java/mekanism/client/render/item/machine/RenderFluidTankItem.java
- src/main/java/mekanism/client/render/tileentity/RenderDynamicTank.java
- src/main/java/mekanism/client/render/tileentity/RenderFluidTank.java
- src/main/java/mekanism/client/render/tileentity/RenderThermalEvaporationController.java
- src/main/java/mekanism/client/render/tileentity/RenderThermoelectricBoiler.java
- src/main/java/mekanism/client/render/transmitter/RenderMechanicalPipe.java
- src/main/java/mekanism/common/MekanismFluids.java
- src/main/java/mekanism/common/network/PacketTransmitterUpdate.java
- src/main/java/mekanism/common/tile/TileEntityFluidTank.java
- src/main/java/mekanism/generators/client/gui/GuiIndustrialTurbine.java
- src/main/java/mekanism/generators/client/gui/GuiReactorHeat.java
- src/main/java/mekanism/generators/client/render/RenderIndustrialTurbine.java
> Make many more Mekanism fluid renderers Stack aware for NBT purposes

- src/main/java/mekanism/client/ClientConnectionHandler.java
- src/main/java/mekanism/client/ClientProxy.java
- src/main/java/mekanism/client/MekanismClient.java
- src/main/java/mekanism/client/MekanismKeyHandler.java
- src/main/java/mekanism/client/voice/VoiceClient.java
- src/main/java/mekanism/client/voice/VoiceInput.java
- src/main/java/mekanism/client/voice/VoiceOutput.java
- src/main/java/mekanism/common/CommonProxy.java
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/config/MekanismConfig.java
- src/main/java/mekanism/common/item/ItemWalkieTalkie.java
- src/main/java/mekanism/common/network/PacketConfigSync.java
- src/main/java/mekanism/common/voice/VoiceConnection.java
- src/main/java/mekanism/common/voice/VoiceServerManager.java
- src/main/resources/assets/mekanism/lang/en_us.lang
- src/main/resources/assets/mekanism/recipes/walkietalkie.json
- Add back the voice server (context can be found here: https://github.com/mekanica/mekanica/pull/137 ) disabled by default
- Cleaned the voice server up so that all the variables in it are not public
- Voice connections now keep track of the uuid of a player rather than the username. (Shouldn't matter given they have to reconnect when changing usernames but it is better to be consistent)
> Readd voice server

- src/main/java/mekanism/client/render/RenderTickHandler.java
- src/main/java/mekanism/common/config/ClientConfig.java
Adds an option so the user can configure their HUD to be on left or right side. Also changes color for the HUD so that the text is readable against the shadow.
> Add support for left/right alignment of HUD

- src/main/java/mekanism/common/network/PacketConfigurationUpdate.java
- src/main/java/mekanism/common/util/MekanismUtils.java
- Fixes issues such as enderio conduit's not disconnecting/reconnecting to a side when we stop supporting a capability on that side due to the machine's configuration changing.
> Notify neighbor on side when our capabilities change due to config

- src/main/java/mekanism/client/gui/GuiDynamicTank.java
- src/main/java/mekanism/client/gui/GuiEmbeddedGaugeTile.java
- src/main/java/mekanism/client/gui/GuiThermoelectricBoiler.java
- src/main/java/mekanism/client/render/MekanismRenderer.java
- src/main/java/mekanism/generators/client/gui/GuiIndustrialTurbine.java
- src/main/java/mekanism/generators/common/tile/turbine/TileEntityTurbineCasing.java
- Fixes a few spots where the color was not drawn for fluidstacks.
- Deduplicated the gauge code for those spots
- Fixed the Industrial Turbine GUI not getting the proper fluid scale.
> Fix a few missing fluid color renders for various guis

- src/main/java/mekanism/client/gui/GuiQuantumEntangloporter.java
- src/main/java/mekanism/client/gui/GuiTeleporter.java
- src/main/java/mekanism/common/block/BlockMachine.java
- src/main/java/mekanism/common/network/PacketSecurityMode.java
- Fixes being unable to let other people view the teleporter/quantum entangloporter (including ops with the bypass config option set)
- Also add the security tab to the corresponding gui's
> Use security utils for checking access to teleporter and quantum entangloporter

- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/integration/MekanismHooks.java
- src/main/java/mekanism/common/integration/OreDictManager.java
This adds compatibility for Mystical Agriculture(implements #5083),
compatibility for Mods adding their own versions of Vanilla Ores
and Compatibility for some Standard Gems(Ruby, Sapphire, Peridot and Topaz).
> Add some more Compatibility

- src/main/java/mekanism/common/content/transporter/StackSearcher.java
- src/main/java/mekanism/common/entity/EntityRobit.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
- src/main/java/mekanism/common/tile/TileEntityFactory.java
- src/main/java/mekanism/common/util/InventoryUtils.java
- src/main/java/mekanism/common/util/StackUtils.java
NB: haven't tested this yet.
A few item stack equality check changes to hopefully fix #5449 & #5435
> Itemstack equality

- src/main/java/mekanism/common/MekanismBlocks.java
- src/main/java/mekanism/common/block/BlockBasic.java
- src/main/java/mekanism/common/block/states/BlockStateBasic.java
- src/main/resources/mekanism_at.cfg
* closes #5444
* Make Refined Obsidian usable for Nether Portals.
> Make Refined Obsidian usable for Nether Portals

- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/content/transporter/StackSearcher.java
- src/main/java/mekanism/common/integration/OreDictManager.java
- src/main/java/mekanism/common/recipe/BinRecipe.java
- src/main/java/mekanism/common/recipe/inputs/InfusionInput.java
- src/main/java/mekanism/common/recipe/inputs/MachineInput.java
- src/main/java/mekanism/common/tile/TileEntityMetallurgicInfuser.java
- src/main/java/mekanism/common/util/StackUtils.java
- Cleans up a bit of infusion code, and makes it query things slightly less often
> Cleanup a bit of infusion code

- src/main/java/mekanism/common/block/BlockBasic.java
- src/main/java/mekanism/common/block/states/BlockStateBasic.java
* make most BlockBasics Opaque for Compatibility(with for example Storage Drawers Framed Drawers)
* make some more BlockBasics full blocks
* change the BlockStateBasic default for full block to true
* Fix BlockBasic Resistance
* Reduce BlockBasic Resistance to match Iron Block
* Reduce Bronze Block, Steel Block, Thermal Evaporation Stuff and Security Desk Resistance to be Iron Block x1.5
* keep Osmium Block Resistance to be Iron Block x2
* Increase Refined Obsidian Hardness to match Obsidian
* Increase Osmium Block Hardness to be Iron Block x 1.5
> BlockBasic Property changes

- src/main/java/mekanism/common/base/IFactory.java
- src/main/java/mekanism/common/config/GeneralConfig.java
- src/main/java/mekanism/common/tile/TileEntityChemicalDissolutionChamber.java
- src/main/java/mekanism/common/tile/TileEntityFactory.java
- src/main/java/mekanism/common/tile/prefab/TileEntityAdvancedElectricMachine.java
- src/main/java/mekanism/common/util/GasUtils.java
- Includes config option to disable feature
> Void gases from machines on load if invalid

- src/main/resources/assets/mekanism/lang/es_es.lang
Edited translation file es_es.lang, Fixed misspellings, syntax errors and changed terms according to the nomenclature, correct technical names and cotextual interpretation.
> es_es.lang update and fixes

- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/integration/OreDictManager.java
* Added PRC Recipes for Coal Gasification making Hydrogen and Sulfur.(#5054)
* Added a Enrichment Chamber Recipe to convert Sulfur back into Gunpowder.
Using Coal Gasification you can get 18900J out of one coal instead of ~6kJ with a Heat Generator.
> Implement #5054(Coal Gasification)

- src/main/java/mekanism/common/integration/OreDictManager.java
Implement the Wood counterpart for Coal Gasification
* Implemented Wood Gasification
* Added a Recipe to convert Sawdust to Charcoal
* Added Slab processing to the Sawmill
Using Wood Gasification you can get 18900J out of one log,
9450J out of one plank or sawdust,
4725J out of one slab and
1890J out of one stick.
> Implement Wood Gasification

- src/main/java/mekanism/common/integration/OreDictManager.java
* Fix Sulfur -> Gunpowder Recipe
* Deduplicate the OreDictManager class
> a small deduplication of the OreDictManager

- src/main/java/mekanism/api/MekanismAPI.java
- src/main/java/mekanism/api/transmitters/DynamicNetwork.java
- src/main/java/mekanism/api/transmitters/TransmitterNetworkRegistry.java
- src/main/java/mekanism/common/tile/transmitter/TileEntityUniversalCable.java
- src/main/java/mekanism/common/transmitters/Transmitter.java
- src/main/java/mekanism/common/transmitters/grid/EnergyNetwork.java
- src/main/java/mekanism/common/transmitters/grid/FluidNetwork.java
- src/main/java/mekanism/common/transmitters/grid/GasNetwork.java
- src/main/java/mekanism/common/transmitters/grid/HeatNetwork.java
- src/main/java/mekanism/common/transmitters/grid/InventoryNetwork.java
- Made EnergyNetwork use a double for capacity (Fixes the remainder of #5576 )
- Minor cleanup of code for networks/energy
> Make EnergyNetwork capacity be a double

- src/main/java/mekanism/common/content/miner/ThreadMinerSearch.java
- src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
Make ThreadMinerSearch use a chunkcache to prevent possible CME's / other issues with non safe world access.
https://github.com/mekanism/Mekanism/issues/5688
> [1.14.X] Make ThreadMinerSearch use a chunk cache.

- src/api/java/mekanism/api/math/FloatingLong.java
- src/test/java/mekanism/api/math/FloatingLongTest.java
Added multiplication and overflow handling
> Floating long energy

- src/main/java/mekanism/common/registries/MekanismFluids.java
so mods that expect realistic temperatures don't break
> set steam temperature for correct interoperability with other mods

- src/main/java/mekanism/client/ClientTickHandler.java
- src/main/java/mekanism/client/render/RenderTickHandler.java
- src/main/java/mekanism/common/CommonPlayerTickHandler.java
- src/main/java/mekanism/common/content/gear/Module.java
- src/main/java/mekanism/common/content/gear/mekasuit/ModuleMekaSuit.java
- src/main/java/mekanism/common/lib/radiation/RadiationManager.java
- src/main/java/mekanism/common/lib/radiation/capability/DefaultRadiationEntity.java
- src/main/java/mekanism/common/util/MekanismUtils.java
* Fix players with a MekaSuit Bodyarmor with a GravitationalModulationUnit enabled falling in spectator mode.
> Fix players with GravitationalModulation MekaSuit falling in spectator mode.

- src/generators/java/mekanism/generators/client/gui/GuiSolarGenerator.java
* Add Solar Generator(and Advanced Solar Generator) energy bar back.
> Add solar generator energy bar back

- src/main/java/mekanism/client/gui/GuiSeismicReader.java
- Fix seismic reader scrolling direction
> Fix seismic reader scrolling buttons

- src/generators/java/mekanism/generators/client/jei/FissionReactorRecipeCategory.java
- Fix Fission Reactor JEI plugin not handling Steam as an Output.
> Fix Fission Reactor JEI plugin not handling Steam as an Output

- src/main/java/mekanism/common/item/gear/ItemFreeRunners.java
- src/main/java/mekanism/common/item/gear/ItemHazmatSuitArmor.java
- src/main/java/mekanism/common/item/gear/ItemJetpack.java
- src/main/java/mekanism/common/item/gear/ItemMekaSuitArmor.java
- src/main/java/mekanism/common/item/gear/ItemScubaMask.java
- src/main/java/mekanism/common/item/gear/ItemScubaTank.java
- Fix some armor items being enchantable that shouldn't be.
> Fix armor items that shouldn't be enchantable being it anyways

- src/main/java/mekanism/common/content/gear/mekasuit/ModuleMekaSuit.java
* Fix Electrolytic Breathing Unit working without water.
This currently only requires your feet to be in water tho.
> Fix Electrolytic Breathing Unit working without water

- src/main/java/mekanism/client/render/tileentity/RenderTeleporter.java
- src/main/java/mekanism/common/network/PacketPortableTeleporterGui.java
- src/main/java/mekanism/common/tile/TileEntityTeleporter.java
* Fix riding entities sometimes being teleported back and forth.
* Allow Teleporter frames to be placed in more orientations like:
* Horizontally on the ground
* Upside Down
> Allow Teleporter Frames to be placed Horizontally

- src/main/java/mekanism/common/entity/EntityRobit.java
- Fix Robit Teleport back home button
Thanks to StormedPanda and Robbal14 for noticing.
> Fix Robit Teleport back home button

- src/main/java/mekanism/client/gui/GuiTeleporter.java
- src/main/java/mekanism/client/gui/item/GuiPortableTeleporter.java
- src/main/java/mekanism/client/gui/qio/GuiQIOFrequencySelect.java
- src/main/java/mekanism/client/render/tileentity/RenderTeleporter.java
- src/main/java/mekanism/common/content/qio/QIOFrequency.java
- src/main/java/mekanism/common/content/teleporter/TeleporterFrequency.java
- src/main/java/mekanism/common/inventory/container/item/PortableTeleporterContainer.java
- src/main/java/mekanism/common/inventory/container/sync/SyncableFrequency.java
- src/main/java/mekanism/common/lib/frequency/Frequency.java
- src/main/java/mekanism/common/network/PacketHandler.java
- src/main/java/mekanism/common/network/PacketPortableTeleporter.java
- src/main/java/mekanism/common/network/PacketPortableTeleporterGui.java
- src/main/java/mekanism/common/network/PacketTeleporterSetColor.java
- src/main/java/mekanism/common/tile/TileEntityTeleporter.java
Not yet working with portable teleporters
Also the colored square isn't auto updating yet.
- Make it possible to color teleporters frequencies
> Implement Teleporter portal coloring

- src/generators/java/mekanism/generators/common/registries/GeneratorsBuilders.java
- src/main/java/mekanism/common/Mekanism.java
- src/main/java/mekanism/common/command/builders/Builders.java
- src/main/java/mekanism/common/command/builders/StructureBuilder.java
- Turbine: Replace some Electromagnetic Coils with Saturating Condensers.
This makes the turbine able to condense all the steam without decreasing energy production at all.
- Boiler: Remove second layer of Superheating Elements and move Pressure Dispersers up.
This greatly increases max achievable boil rate, by increasing the water capacity.
- Fusion Reactor: Remove some useless Casings.
This just makes it look more how most people build it.
- Added SPS: Builds an SPS without any ports or Supercharged Coils.
- Fission Reactor: Fill empty columns with air.
This makes it so you no longer have to clean these single columns if you built it into something.
> Improve /mek build structures

- src/main/java/mekanism/common/registration/impl/ItemDeferredRegister.java
- src/main/java/mekanism/common/registries/MekanismItems.java
- Make Meka-Tool and Mekasuit fire & lava proof
They make you immune to fire, so why should they burn?
> Make Meka-Tool and Armor lava proof

- src/main/java/mekanism/client/jei/machine/NucleosynthesizingRecipeCategory.java
> Fix Nucleosynthesizer antimatter display(#6739)

- README.md
Yeah, not a big PR, but a small change. ^^
Just changed the version in the README.md
> Updated the version

- src/api/java/mekanism/api/math/FloatingLong.java
- src/test/java/mekanism/api/math/FloatingLongPropertyTest.java
- src/test/java/mekanism/api/math/FloatingLongTest.java
Fixed division algorithm edge cases, added the improved test coverage by @pupnewfster 
Ran 1M property test cases twice, passed both times. Also added some edge cases to the regular test library. Used Wolfram alpha to confirm accuracy.
> Division Algorithm Fixes/Optimizations

- src/main/java/mekanism/common/tile/machine/TileEntitySolarNeutronActivator.java
Added canSeeSun ComputerMethod for SNA
> Added canSeeSun ComputerMethod for SNA

- build.gradle
- gradle.properties
- src/api/java/mekanism/api/chemical/ChemicalTankBuilder.java
- src/api/java/mekanism/api/functions/ConstantPredicates.java
- src/generators/java/mekanism/generators/common/content/fission/FissionReactorMultiblockData.java
- src/main/java/mekanism/client/ClientRegistration.java
- src/main/java/mekanism/client/gui/GuiUtils.java
- src/main/java/mekanism/client/render/item/ChemicalFluidBarDecorator.java
- src/main/java/mekanism/client/render/item/MekaSuitBarDecorator.java
- src/main/java/mekanism/common/capabilities/GenericTankSpec.java
- src/main/java/mekanism/common/capabilities/chemical/item/ChemicalTankSpec.java
- src/main/java/mekanism/common/capabilities/chemical/item/RateLimitMultiTankGasHandler.java
- src/main/java/mekanism/common/capabilities/fluid/BasicFluidTank.java
- src/main/java/mekanism/common/capabilities/fluid/item/RateLimitMultiTankFluidHandler.java
- src/main/java/mekanism/common/content/boiler/BoilerMultiblockData.java
- src/main/java/mekanism/common/inventory/slot/BasicInventorySlot.java
- src/main/java/mekanism/common/item/gear/ItemFlamethrower.java
- src/main/java/mekanism/common/item/gear/ItemGasArmor.java
- src/main/java/mekanism/common/item/gear/ItemMekaSuitArmor.java
- src/main/java/mekanism/common/util/FluidUtils.java
- src/main/resources/META-INF/accesstransformer.cfg
This PR renders an additional bar on the mekasuit helmet and bodyarmor showing the fluid/gas amount if the required module is present in the color of the fluid/chemical.
This also updates forge and minecraft dependencies and version ranges to a supported version of this feature
> Added ItemDecorator for Mekasuit helmet / bodyarmor
